package com.mino.devjob.recruit.service;

import static org.mockito.Mockito.*;

import java.net.URI;
import java.util.function.Function;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Answers;
import org.mockito.ArgumentMatchers;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.web.reactive.function.client.WebClient;
import org.springframework.web.util.UriBuilder;

import com.mino.devjob.recruit.model.Recruit;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import reactor.test.StepVerifier;

@ExtendWith(MockitoExtension.class)
class CrawlKakaoServiceTest {
	@InjectMocks
	private CrawlKakaoService crawlKakao;
	@Mock(answer = Answers.RETURNS_DEEP_STUBS)
	private WebClient webClientMock;

	@Test
	void crawl() {
		when(webClientMock.get()
			.uri(ArgumentMatchers.<Function<UriBuilder, URI>>any())
			.retrieve().bodyToMono(ArgumentMatchers.<Class<String>>any()))
			.thenReturn(Mono.just(str));

		Flux<Recruit> kakaoRecruits = crawlKakao.crawl();

		StepVerifier.create(kakaoRecruits)
			.expectNextCount(15)
			.verifyComplete();
	}

	private final String str = "\n"
		+ "<!doctype html>\n"
		+ "<html lang=\"ko\">\n"
		+ "<body class=\"ko\">\n"
		+ "\n"
		+ "<div id=\"kakaoWrap\" >\n"
		+ "    <!-- kakaoContent -->\n"
		+ "    <div id=\"kakaoContent\" class=\"cont_job\" role=\"main\">\n"
		+ "        <div id=\"cMain\">\n"
		+ "            <div id=\"mArticle\">\n"
		+ "                <div class=\"wrap_recruit sub_recruit\">\n"
		+ "                    <!-- <h3 class=\"tit_notice\">진행중 공고</h3> -->\n"
		+ "                    <!-- 2017-09-15 직무선택 탭 추가 -->\n"
		+ "                    <!-- 2017-09-18 직무선택 탭 수정 -->\n"
		+ "                    <!-- 2020-04-08 직무선택 탭 수정 시작 -->\n"
		+ "                    <strong class=\"screen_out\">직무 선택 메뉴</strong>\n"
		+ "                    <ul id=\"jobTypeList\" class=\"tab_job\"> <!-- 2020-04-08 클래스 변경(.tab_group -> .tab_job) -->\n"
		+ "\n"
		+ "\n"
		+ "                        <li class=\"on\">\n"
		+ "                            <a href=\"javascript:void(0);\" data-part=\"TECHNOLOGY\" data-skilset=\"\" class=\"link_job link_job1\">\n"
		+ "                                <span class=\"txt_tab\">테크</span>\n"
		+ "                                <span class=\"emph_num\">\n"
		+ "                                                                            15\n"
		+ "                                                                    </span>\n"
		+ "                            </a>\n"
		+ "                        </li>\n"
		+ "\n"
		+ "\n"
		+ "                        <li class=\"\">\n"
		+ "                            <a href=\"javascript:void(0);\" data-part=\"BUSINESS_SERVICES\" data-skilset=\"\" class=\"link_job link_job2\">\n"
		+ "                                <span class=\"txt_tab\">서비스비즈</span>\n"
		+ "                                <span class=\"emph_num\">\n"
		+ "                                                                            56\n"
		+ "                                                                    </span>\n"
		+ "                            </a>\n"
		+ "                        </li>\n"
		+ "\n"
		+ "\n"
		+ "                        <li class=\"\">\n"
		+ "                            <a href=\"javascript:void(0);\" data-part=\"DESIGN/BRAND_MARKETING\" data-skilset=\"\" class=\"link_job link_job3\">\n"
		+ "                                <span class=\"txt_tab\">디자인/브랜드</span>\n"
		+ "                                <span class=\"emph_num\">\n"
		+ "                                                                            22\n"
		+ "                                                                    </span>\n"
		+ "                            </a>\n"
		+ "                        </li>\n"
		+ "\n"
		+ "\n"
		+ "                        <li class=\"\">\n"
		+ "                            <a href=\"javascript:void(0);\" data-part=\"STAFF\" data-skilset=\"\" class=\"link_job link_job4\">\n"
		+ "                                <span class=\"txt_tab\">스태프</span>\n"
		+ "                                <span class=\"emph_num\">\n"
		+ "                                                                            21\n"
		+ "                                                                    </span>\n"
		+ "                            </a>\n"
		+ "                        </li>\n"
		+ "                    </ul>\n"
		+ "                    <!-- //2020-04-08 직무선택 탭 수정 끝 -->\n"
		+ "                    <!-- // 2017-09-19 직무선택 탭 수정 -->\n"
		+ "                    <!-- 2020-04-08 서브메뉴 추가 시작 -->\n"
		+ "                    <div class=\"wrap_submenu\">\n"
		+ "                        <div class=\"inner_submenu\">\n"
		+ "                            <div class=\"box_select\">\n"
		+ "                                <strong class=\"screen_out\">회사 정보</strong>\n"
		+ "                                <em class=\"screen_out\">선택내용</em>\n"
		+ "                                <a href=\"javascript:void(0);\" class=\"link_selected\">\n"
		+ "                                    전체\n"
		+ "                                    <span class=\"ico_arr\"></span>\n"
		+ "                                </a>\n"
		+ "                                <em class=\"screen_out\">선택옵션</em>\n"
		+ "                                <ul id=\"companySelect\" class=\"list_opt\">\n"
		+ "                                    <li  class=\"on\">\n"
		+ "                                        <a href=\"#\" data-company=\"ALL\" class=\"link_option\"><span class=\"txt_option\">전체</span></a>\n"
		+ "                                    </li>\n"
		+ "                                    <li >\n"
		+ "                                        <a href=\"#\" data-company=\"KAKAO\" class=\"link_option\"><span class=\"txt_option\">카카오</span></a>\n"
		+ "                                    </li>\n"
		+ "                                    <li >\n"
		+ "                                        <a href=\"#\" data-company=\"SUBSIDIARY\" class=\"link_option\"><span class=\"txt_option\">관계사</span></a>\n"
		+ "                                    </li>\n"
		+ "                                    <li >\n"
		+ "                                        <a href=\"#\" data-company=\"SUBSIDIARY_GROUP\" class=\"link_option\"><span class=\"txt_option\">관계사별 모아보기</span></a> <!-- 2020-04-14 수정 -->\n"
		+ "                                    </li>\n"
		+ "                                </ul>\n"
		+ "                            </div>\n"
		+ "                            <div class=\"box_select\">\n"
		+ "                                <strong class=\"screen_out\">전체 직원유형</strong>\n"
		+ "                                <em class=\"screen_out\">선택내용</em>\n"
		+ "                                <a href=\"javascript:void(0);\" class=\"link_selected\">\n"
		+ "                                    전체 직원유형\n"
		+ "                                    <span class=\"ico_arr\"></span>\n"
		+ "                                </a>\n"
		+ "                                <em class=\"screen_out\">선택옵션</em>\n"
		+ "                                <ul id=\"employeeTypeList\" class=\"list_opt\">\n"
		+ "                                    <li   class=\"on\"  >\n"
		+ "                                        <a href=\"javascript:void(0);\" data-employee-type=\"\" class=\"link_option\"><span class=\"txt_option\">전체 직원유형</span></a>\n"
		+ "                                    </li>\n"
		+ "                                    <li   >\n"
		+ "                                        <a href=\"javascript:void(0);\" data-employee-type=\"Full Time\" class=\"link_option\"><span class=\"txt_option\">정규직</span></a>\n"
		+ "                                    </li>\n"
		+ "                                    <li   >\n"
		+ "                                        <a href=\"javascript:void(0);\" data-employee-type=\"Seasonal\" class=\"link_option\"><span class=\"txt_option\">계약직</span></a>\n"
		+ "                                    </li>\n"
		+ "                                    <li   >\n"
		+ "                                        <a href=\"javascript:void(0);\" data-employee-type=\"Intern\" class=\"link_option\"><span class=\"txt_option\">인턴</span></a>\n"
		+ "                                    </li>\n"
		+ "                                    <li   >\n"
		+ "                                        <a href=\"javascript:void(0);\" data-employee-type=\"Part Time\" class=\"link_option\"><span class=\"txt_option\">어시스턴트</span></a>\n"
		+ "                                    </li>\n"
		+ "                                </ul>\n"
		+ "                            </div>\n"
		+ "                            <form id=\"formSearch\" name=\"search\" method=\"get\" class=\"wrap_search\">\n"
		+ "                                <fieldset>\n"
		+ "                                    <legend class=\"screen_out\">검색</legend>\n"
		+ "                                    <div id=\"box_search\"   class=\"box_searchbar\"  >\n"
		+ "                                        <!-- 입력시 state_on 추가 -->\n"
		+ "                                        <label for=\"noticeSearch\" class=\"lab_search\">검색어를 입력하세요.</label> <!-- 2020-04-21 수정 -->\n"
		+ "                                        <input type=\"text\" class=\"tf_search\" id=\"noticeSearch\" name=\"keyword\" value=\"\" autocomplete=\"off\" title=\"검색어를 입력하세요.\"> <!-- 2020-04-21 수정 -->\n"
		+ "                                        <button type=\"button\" id=\"searchBtn\" class=\"btn_search ico_recruit\">\n"
		+ "                                            <span class=\"ir_wa\">검색</span>\n"
		+ "                                        </button>\n"
		+ "                                    </div>\n"
		+ "                                </fieldset>\n"
		+ "                            </form>\n"
		+ "                        </div>\n"
		+ "                    </div>\n"
		+ "                    <!-- //2020-04-08 서브메뉴 추가 끝 -->\n"
		+ "                    <!-- 2017-08-18 영입 직군 태그 추가 -->\n"
		+ "                    <div class=\"searchTag wrap_tag\">\n"
		+ "                        <strong class=\"screen_out\">직군 태그</strong>\n"
		+ "                        <!-- 2020-06-16 클래스명 수정 -->\n"
		+ "                        <p class=\"desc_tag\">* 아래 관심 있는 #해시태그를 선택하시면, 해당 스킬셋과 관련된 공고를 확인하실 수 있습니다.</p>\n"
		+ "                        <div class=\"area_tag\">\n"
		+ "                            <a href=\"javascript:void(0);\"   class=\"tag_group\"  data-skilset=\"\" data-code=\"Android\">\n"
		+ "                                #Android\n"
		+ "                            </a>\n"
		+ "                            <a href=\"javascript:void(0);\"   class=\"tag_group\"  data-skilset=\"\" data-code=\"iOS\">\n"
		+ "                                #iOS\n"
		+ "                            </a>\n"
		+ "                            <a href=\"javascript:void(0);\"   class=\"tag_group\"  data-skilset=\"\" data-code=\"Windows\">\n"
		+ "                                #Windows\n"
		+ "                            </a>\n"
		+ "                            <a href=\"javascript:void(0);\"   class=\"tag_group\"  data-skilset=\"\" data-code=\"Web_front\">\n"
		+ "                                #Web front\n"
		+ "                            </a>\n"
		+ "                            <a href=\"javascript:void(0);\"   class=\"tag_group\"  data-skilset=\"\" data-code=\"DB\">\n"
		+ "                                #DB\n"
		+ "                            </a>\n"
		+ "                            <a href=\"javascript:void(0);\"   class=\"tag_group\"  data-skilset=\"\" data-code=\"Cloud\">\n"
		+ "                                #Cloud\n"
		+ "                            </a>\n"
		+ "                            <a href=\"javascript:void(0);\"   class=\"tag_group\"  data-skilset=\"\" data-code=\"System\">\n"
		+ "                                #System\n"
		+ "                            </a>\n"
		+ "                            <a href=\"javascript:void(0);\"   class=\"tag_group\"  data-skilset=\"\" data-code=\"Network\">\n"
		+ "                                #Network\n"
		+ "                            </a>\n"
		+ "                            <a href=\"javascript:void(0);\"   class=\"tag_group\"  data-skilset=\"\" data-code=\"Security\">\n"
		+ "                                #Security\n"
		+ "                            </a>\n"
		+ "                            <a href=\"javascript:void(0);\"   class=\"tag_group\"  data-skilset=\"\" data-code=\"Algorithm_ML\">\n"
		+ "                                #Algorithm/ML\n"
		+ "                            </a>\n"
		+ "                            <a href=\"javascript:void(0);\"   class=\"tag_group\"  data-skilset=\"\" data-code=\"Algorithm_Ranking\">\n"
		+ "                                #Algorithm/Ranking\n"
		+ "                            </a>\n"
		+ "                            <a href=\"javascript:void(0);\"   class=\"tag_group\"  data-skilset=\"\" data-code=\"Hadoop_eco_system\">\n"
		+ "                                #Hadoop eco system\n"
		+ "                            </a>\n"
		+ "                            <a href=\"javascript:void(0);\"   class=\"tag_group\"  data-skilset=\"\" data-code=\"Server\">\n"
		+ "                                #Server\n"
		+ "                            </a>\n"
		+ "                            <a href=\"javascript:void(0);\"   class=\"tag_group\"  data-skilset=\"\" data-code=\"Statistics_Analysis\">\n"
		+ "                                #Statistics/Analysis\n"
		+ "                            </a>\n"
		+ "                            <a href=\"javascript:void(0);\"   class=\"tag_group\"  data-skilset=\"\" data-code=\"NLP\">\n"
		+ "                                #NLP\n"
		+ "                            </a>\n"
		+ "                            <a href=\"javascript:void(0);\"   class=\"tag_group\"  data-skilset=\"\" data-code=\"NLP_Linguist\">\n"
		+ "                                #NLP linguist\n"
		+ "                            </a>\n"
		+ "                            <a href=\"javascript:void(0);\"   class=\"tag_group\"  data-skilset=\"\" data-code=\"QA\">\n"
		+ "                                #QA\n"
		+ "                            </a>\n"
		+ "                            <a href=\"javascript:void(0);\"   class=\"tag_group\"  data-skilset=\"\" data-code=\"etc\">\n"
		+ "                                #기타\n"
		+ "                            </a>\n"
		+ "                        </div>\n"
		+ "                    </div>\n"
		+ "                    <!-- 2020-04-08 추가 시작 -->\n"
		+ "\n"
		+ "                    <ul class=\"list_jobs\">\n"
		+ "                        <li  style=\"background-color: #FFFDEE;\" >\n"
		+ "                            <div class=\"area_info\">\n"
		+ "                                <div class=\"wrap_info\">\n"
		+ "                                    <a href=\"/jobs/P-11150?part=TECHNOLOGY&page=1&company=ALL\" class=\"link_jobs\">\n"
		+ "                                        <h4 class=\"tit_jobs\">[경력] 빅데이터 플랫폼 엔지니어 모집</h4>\n"
		+ "                                    </a>\n"
		+ "                                    <dl class=\"list_info\">\n"
		+ "                                        <dt class=\"screen_out\">영입마감일</dt>\n"
		+ "                                        <dd>영입종료시</dd>\n"
		+ "                                        <dt class=\"screen_out\">근무지</dt>\n"
		+ "                                        <dd>판교</dd>\n"
		+ "                                    </dl>\n"
		+ "                                    <div class=\"list_tag wrap_tag\">\n"
		+ "                                        <strong class=\"screen_out\">직군 태그</strong>\n"
		+ "                                        <a href=\"javascript:void(0);\" data-code=\"Hadoop_eco_system\" class=\"link_tag\">\n"
		+ "                                            <span class=\"txt_hash\">#</span>Hadoop eco system\n"
		+ "                                        </a>\n"
		+ "                                    </div>\n"
		+ "                                </div>\n"
		+ "                                <dl class=\"item_subinfo\">\n"
		+ "                                    <dt class=\"screen_out\">회사정보</dt>\n"
		+ "                                    <dd>카카오</dd>\n"
		+ "                                </dl>\n"
		+ "                                <dl class=\"item_subinfo\">\n"
		+ "                                    <dt class=\"screen_out\">직원유형</dt>\n"
		+ "                                    <dd>정규직</dd>\n"
		+ "                                </dl>\n"
		+ "                            </div>\n"
		+ "                        </li>\n"
		+ "                        <li  style=\"background-color: #FFFDEE;\" >\n"
		+ "                            <div class=\"area_info\">\n"
		+ "                                <div class=\"wrap_info\">\n"
		+ "                                    <a href=\"/jobs/P-11742?part=TECHNOLOGY&page=1&company=ALL\" class=\"link_jobs\">\n"
		+ "                                        <h4 class=\"tit_jobs\">[월간 카카오 9월] 사용자 서비스 클라이언트 개발자 모집</h4>\n"
		+ "                                    </a>\n"
		+ "                                    <dl class=\"list_info\">\n"
		+ "                                        <dt class=\"screen_out\">영입마감일</dt>\n"
		+ "                                        <dd>영입종료시</dd>\n"
		+ "                                        <dt class=\"screen_out\">근무지</dt>\n"
		+ "                                        <dd>판교</dd>\n"
		+ "                                    </dl>\n"
		+ "                                    <div class=\"list_tag wrap_tag\">\n"
		+ "                                        <strong class=\"screen_out\">직군 태그</strong>\n"
		+ "                                        <a href=\"javascript:void(0);\" data-code=\"Android\" class=\"link_tag\">\n"
		+ "                                            <span class=\"txt_hash\">#</span>Android\n"
		+ "                                        </a>\n"
		+ "                                        <a href=\"javascript:void(0);\" data-code=\"iOS\" class=\"link_tag\">\n"
		+ "                                            <span class=\"txt_hash\">#</span>iOS\n"
		+ "                                        </a>\n"
		+ "                                        <a href=\"javascript:void(0);\" data-code=\"Web_front\" class=\"link_tag\">\n"
		+ "                                            <span class=\"txt_hash\">#</span>Web front\n"
		+ "                                        </a>\n"
		+ "                                    </div>\n"
		+ "                                </div>\n"
		+ "                                <dl class=\"item_subinfo\">\n"
		+ "                                    <dt class=\"screen_out\">회사정보</dt>\n"
		+ "                                    <dd>카카오</dd>\n"
		+ "                                </dl>\n"
		+ "                                <dl class=\"item_subinfo\">\n"
		+ "                                    <dt class=\"screen_out\">직원유형</dt>\n"
		+ "                                    <dd>정규직</dd>\n"
		+ "                                </dl>\n"
		+ "                            </div>\n"
		+ "                        </li>\n"
		+ "                        <li >\n"
		+ "                            <div class=\"area_info\">\n"
		+ "                                <div class=\"wrap_info\">\n"
		+ "                                    <a href=\"/jobs/P-11750?part=TECHNOLOGY&page=1&company=ALL\" class=\"link_jobs\">\n"
		+ "                                        <h4 class=\"tit_jobs\">2021 카카오 신입개발자 블라인드 채용 - 인프라/프로그래밍 분야 소개</h4>\n"
		+ "                                    </a>\n"
		+ "                                    <dl class=\"list_info\">\n"
		+ "                                        <dt class=\"screen_out\">영입마감일</dt>\n"
		+ "                                        <dd>영입종료시</dd>\n"
		+ "                                        <dt class=\"screen_out\">근무지</dt>\n"
		+ "                                        <dd>판교</dd>\n"
		+ "                                    </dl>\n"
		+ "                                    <div class=\"list_tag wrap_tag\">\n"
		+ "                                        <strong class=\"screen_out\">직군 태그</strong>\n"
		+ "                                        <a href=\"javascript:void(0);\" data-code=\"etc\" class=\"link_tag\">\n"
		+ "                                            <span class=\"txt_hash\">#</span>기타\n"
		+ "                                        </a>\n"
		+ "                                    </div>\n"
		+ "                                </div>\n"
		+ "                                <dl class=\"item_subinfo\">\n"
		+ "                                    <dt class=\"screen_out\">회사정보</dt>\n"
		+ "                                    <dd>카카오</dd>\n"
		+ "                                </dl>\n"
		+ "                                <dl class=\"item_subinfo\">\n"
		+ "                                    <dt class=\"screen_out\">직원유형</dt>\n"
		+ "                                    <dd>정규직</dd>\n"
		+ "                                </dl>\n"
		+ "                            </div>\n"
		+ "                        </li>\n"
		+ "                        <li >\n"
		+ "                            <div class=\"area_info\">\n"
		+ "                                <div class=\"wrap_info\">\n"
		+ "                                    <a href=\"/jobs/S-1137?part=TECHNOLOGY&page=1&company=ALL\" class=\"link_jobs\">\n"
		+ "                                        <h4 class=\"tit_jobs\">[관계사] 카카오엔터프라이즈 클라우드플랫폼 데이터베이스 엔지니어 모집</h4>\n"
		+ "                                    </a>\n"
		+ "                                    <dl class=\"list_info\">\n"
		+ "                                        <dt class=\"screen_out\">영입마감일</dt>\n"
		+ "                                        <dd>영입종료시</dd>\n"
		+ "                                    </dl>\n"
		+ "                                </div>\n"
		+ "                                <dl class=\"item_subinfo\">\n"
		+ "                                    <dt class=\"screen_out\">회사정보</dt>\n"
		+ "                                    <dd>카카오엔터프라이즈</dd>\n"
		+ "                                </dl>\n"
		+ "                                <dl class=\"item_subinfo\">\n"
		+ "                                    <dt class=\"screen_out\">직원유형</dt>\n"
		+ "                                    <dd>정규직</dd>\n"
		+ "                                </dl>\n"
		+ "                            </div>\n"
		+ "                        </li>\n"
		+ "                        <li >\n"
		+ "                            <div class=\"area_info\">\n"
		+ "                                <div class=\"wrap_info\">\n"
		+ "                                    <a href=\"/jobs/P-9349?part=TECHNOLOGY&page=1&company=ALL\" class=\"link_jobs\">\n"
		+ "                                        <h4 class=\"tit_jobs\">카카오 전문연구요원(전직 및 보충역) 모집</h4>\n"
		+ "                                    </a>\n"
		+ "                                    <dl class=\"list_info\">\n"
		+ "                                        <dt class=\"screen_out\">영입마감일</dt>\n"
		+ "                                        <dd>영입종료시</dd>\n"
		+ "                                        <dt class=\"screen_out\">근무지</dt>\n"
		+ "                                        <dd>판교</dd>\n"
		+ "                                    </dl>\n"
		+ "                                    <div class=\"list_tag wrap_tag\">\n"
		+ "                                        <strong class=\"screen_out\">직군 태그</strong>\n"
		+ "                                        <a href=\"javascript:void(0);\" data-code=\"Android\" class=\"link_tag\">\n"
		+ "                                            <span class=\"txt_hash\">#</span>Android\n"
		+ "                                        </a>\n"
		+ "                                        <a href=\"javascript:void(0);\" data-code=\"iOS\" class=\"link_tag\">\n"
		+ "                                            <span class=\"txt_hash\">#</span>iOS\n"
		+ "                                        </a>\n"
		+ "                                        <a href=\"javascript:void(0);\" data-code=\"Windows\" class=\"link_tag\">\n"
		+ "                                            <span class=\"txt_hash\">#</span>Windows\n"
		+ "                                        </a>\n"
		+ "                                        <a href=\"javascript:void(0);\" data-code=\"Web_front\" class=\"link_tag\">\n"
		+ "                                            <span class=\"txt_hash\">#</span>Web front\n"
		+ "                                        </a>\n"
		+ "                                        <a href=\"javascript:void(0);\" data-code=\"System\" class=\"link_tag\">\n"
		+ "                                            <span class=\"txt_hash\">#</span>System\n"
		+ "                                        </a>\n"
		+ "                                        <a href=\"javascript:void(0);\" data-code=\"Network\" class=\"link_tag\">\n"
		+ "                                            <span class=\"txt_hash\">#</span>Network\n"
		+ "                                        </a>\n"
		+ "                                        <a href=\"javascript:void(0);\" data-code=\"Cloud\" class=\"link_tag\">\n"
		+ "                                            <span class=\"txt_hash\">#</span>Cloud\n"
		+ "                                        </a>\n"
		+ "                                        <a href=\"javascript:void(0);\" data-code=\"DB\" class=\"link_tag\">\n"
		+ "                                            <span class=\"txt_hash\">#</span>DB\n"
		+ "                                        </a>\n"
		+ "                                        <a href=\"javascript:void(0);\" data-code=\"Security\" class=\"link_tag\">\n"
		+ "                                            <span class=\"txt_hash\">#</span>Security\n"
		+ "                                        </a>\n"
		+ "                                        <a href=\"javascript:void(0);\" data-code=\"Algorithm_ML\" class=\"link_tag\">\n"
		+ "                                            <span class=\"txt_hash\">#</span>Algorithm/ML\n"
		+ "                                        </a>\n"
		+ "                                        <a href=\"javascript:void(0);\" data-code=\"Algorithm_Ranking\" class=\"link_tag\">\n"
		+ "                                            <span class=\"txt_hash\">#</span>Algorithm/Ranking\n"
		+ "                                        </a>\n"
		+ "                                        <a href=\"javascript:void(0);\" data-code=\"Hadoop_eco_system\" class=\"link_tag\">\n"
		+ "                                            <span class=\"txt_hash\">#</span>Hadoop eco system\n"
		+ "                                        </a>\n"
		+ "                                        <a href=\"javascript:void(0);\" data-code=\"Server\" class=\"link_tag\">\n"
		+ "                                            <span class=\"txt_hash\">#</span>Server\n"
		+ "                                        </a>\n"
		+ "                                        <a href=\"javascript:void(0);\" data-code=\"Statistics_Analysis\" class=\"link_tag\">\n"
		+ "                                            <span class=\"txt_hash\">#</span>Statistics/Analysis\n"
		+ "                                        </a>\n"
		+ "                                        <a href=\"javascript:void(0);\" data-code=\"etc\" class=\"link_tag\">\n"
		+ "                                            <span class=\"txt_hash\">#</span>기타\n"
		+ "                                        </a>\n"
		+ "                                    </div>\n"
		+ "                                </div>\n"
		+ "                                <dl class=\"item_subinfo\">\n"
		+ "                                    <dt class=\"screen_out\">회사정보</dt>\n"
		+ "                                    <dd>카카오</dd>\n"
		+ "                                </dl>\n"
		+ "                                <dl class=\"item_subinfo\">\n"
		+ "                                    <dt class=\"screen_out\">직원유형</dt>\n"
		+ "                                    <dd>정규직</dd>\n"
		+ "                                </dl>\n"
		+ "                            </div>\n"
		+ "                        </li>\n"
		+ "                        <li >\n"
		+ "                            <div class=\"area_info\">\n"
		+ "                                <div class=\"wrap_info\">\n"
		+ "                                    <a href=\"/jobs/P-11765?part=TECHNOLOGY&page=1&company=ALL\" class=\"link_jobs\">\n"
		+ "                                        <h4 class=\"tit_jobs\">데이터센터 시스템 운영 엔지니어 모집 (경력)</h4>\n"
		+ "                                    </a>\n"
		+ "                                    <dl class=\"list_info\">\n"
		+ "                                        <dt class=\"screen_out\">영입마감일</dt>\n"
		+ "                                        <dd>영입종료시</dd>\n"
		+ "                                        <dt class=\"screen_out\">근무지</dt>\n"
		+ "                                        <dd>판교</dd>\n"
		+ "                                    </dl>\n"
		+ "                                    <div class=\"list_tag wrap_tag\">\n"
		+ "                                        <strong class=\"screen_out\">직군 태그</strong>\n"
		+ "                                        <a href=\"javascript:void(0);\" data-code=\"etc\" class=\"link_tag\">\n"
		+ "                                            <span class=\"txt_hash\">#</span>기타\n"
		+ "                                        </a>\n"
		+ "                                    </div>\n"
		+ "                                </div>\n"
		+ "                                <dl class=\"item_subinfo\">\n"
		+ "                                    <dt class=\"screen_out\">회사정보</dt>\n"
		+ "                                    <dd>카카오</dd>\n"
		+ "                                </dl>\n"
		+ "                                <dl class=\"item_subinfo\">\n"
		+ "                                    <dt class=\"screen_out\">직원유형</dt>\n"
		+ "                                    <dd>정규직</dd>\n"
		+ "                                </dl>\n"
		+ "                            </div>\n"
		+ "                        </li>\n"
		+ "                        <li >\n"
		+ "                            <div class=\"area_info\">\n"
		+ "                                <div class=\"wrap_info\">\n"
		+ "                                    <a href=\"/jobs/S-1684?part=TECHNOLOGY&page=1&company=ALL\" class=\"link_jobs\">\n"
		+ "                                        <h4 class=\"tit_jobs\">[관계사] 키위플러스 2020년 QA 채용형 인턴 모집</h4>\n"
		+ "                                    </a>\n"
		+ "                                    <dl class=\"list_info\">\n"
		+ "                                        <dt class=\"screen_out\">영입마감일</dt>\n"
		+ "                                        <dd>영입종료시</dd>\n"
		+ "                                    </dl>\n"
		+ "                                </div>\n"
		+ "                                <dl class=\"item_subinfo\">\n"
		+ "                                    <dt class=\"screen_out\">회사정보</dt>\n"
		+ "                                    <dd>키위플러스</dd>\n"
		+ "                                </dl>\n"
		+ "                                <dl class=\"item_subinfo\">\n"
		+ "                                    <dt class=\"screen_out\">직원유형</dt>\n"
		+ "                                    <dd>인턴</dd>\n"
		+ "                                </dl>\n"
		+ "                            </div>\n"
		+ "                        </li>\n"
		+ "                        <li >\n"
		+ "                            <div class=\"area_info\">\n"
		+ "                                <div class=\"wrap_info\">\n"
		+ "                                    <a href=\"/jobs/P-11627?part=TECHNOLOGY&page=1&company=ALL\" class=\"link_jobs\">\n"
		+ "                                        <h4 class=\"tit_jobs\">협업도구 및 코드관리도구 운영담당자 모집 (경력)</h4>\n"
		+ "                                    </a>\n"
		+ "                                    <dl class=\"list_info\">\n"
		+ "                                        <dt class=\"screen_out\">영입마감일</dt>\n"
		+ "                                        <dd>영입종료시</dd>\n"
		+ "                                        <dt class=\"screen_out\">근무지</dt>\n"
		+ "                                        <dd>판교</dd>\n"
		+ "                                    </dl>\n"
		+ "                                    <div class=\"list_tag wrap_tag\">\n"
		+ "                                        <strong class=\"screen_out\">직군 태그</strong>\n"
		+ "                                        <a href=\"javascript:void(0);\" data-code=\"etc\" class=\"link_tag\">\n"
		+ "                                            <span class=\"txt_hash\">#</span>기타\n"
		+ "                                        </a>\n"
		+ "                                    </div>\n"
		+ "                                </div>\n"
		+ "                                <dl class=\"item_subinfo\">\n"
		+ "                                    <dt class=\"screen_out\">회사정보</dt>\n"
		+ "                                    <dd>카카오</dd>\n"
		+ "                                </dl>\n"
		+ "                                <dl class=\"item_subinfo\">\n"
		+ "                                    <dt class=\"screen_out\">직원유형</dt>\n"
		+ "                                    <dd>정규직</dd>\n"
		+ "                                </dl>\n"
		+ "                            </div>\n"
		+ "                        </li>\n"
		+ "                        <li >\n"
		+ "                            <div class=\"area_info\">\n"
		+ "                                <div class=\"wrap_info\">\n"
		+ "                                    <a href=\"/jobs/P-11759?part=TECHNOLOGY&page=1&company=ALL\" class=\"link_jobs\">\n"
		+ "                                        <h4 class=\"tit_jobs\">데이터센터 시설 관리 엔지니어 모집 (경력)</h4>\n"
		+ "                                    </a>\n"
		+ "                                    <dl class=\"list_info\">\n"
		+ "                                        <dt class=\"screen_out\">영입마감일</dt>\n"
		+ "                                        <dd>영입종료시</dd>\n"
		+ "                                        <dt class=\"screen_out\">근무지</dt>\n"
		+ "                                        <dd>판교</dd>\n"
		+ "                                    </dl>\n"
		+ "                                    <div class=\"list_tag wrap_tag\">\n"
		+ "                                        <strong class=\"screen_out\">직군 태그</strong>\n"
		+ "                                        <a href=\"javascript:void(0);\" data-code=\"etc\" class=\"link_tag\">\n"
		+ "                                            <span class=\"txt_hash\">#</span>기타\n"
		+ "                                        </a>\n"
		+ "                                    </div>\n"
		+ "                                </div>\n"
		+ "                                <dl class=\"item_subinfo\">\n"
		+ "                                    <dt class=\"screen_out\">회사정보</dt>\n"
		+ "                                    <dd>카카오</dd>\n"
		+ "                                </dl>\n"
		+ "                                <dl class=\"item_subinfo\">\n"
		+ "                                    <dt class=\"screen_out\">직원유형</dt>\n"
		+ "                                    <dd>정규직</dd>\n"
		+ "                                </dl>\n"
		+ "                            </div>\n"
		+ "                        </li>\n"
		+ "                        <li >\n"
		+ "                            <div class=\"area_info\">\n"
		+ "                                <div class=\"wrap_info\">\n"
		+ "                                    <a href=\"/jobs/P-11758?part=TECHNOLOGY&page=1&company=ALL\" class=\"link_jobs\">\n"
		+ "                                        <h4 class=\"tit_jobs\">데이터센터 기계 설비 엔지니어 모집 (경력)</h4>\n"
		+ "                                    </a>\n"
		+ "                                    <dl class=\"list_info\">\n"
		+ "                                        <dt class=\"screen_out\">영입마감일</dt>\n"
		+ "                                        <dd>영입종료시</dd>\n"
		+ "                                        <dt class=\"screen_out\">근무지</dt>\n"
		+ "                                        <dd>판교</dd>\n"
		+ "                                    </dl>\n"
		+ "                                    <div class=\"list_tag wrap_tag\">\n"
		+ "                                        <strong class=\"screen_out\">직군 태그</strong>\n"
		+ "                                        <a href=\"javascript:void(0);\" data-code=\"etc\" class=\"link_tag\">\n"
		+ "                                            <span class=\"txt_hash\">#</span>기타\n"
		+ "                                        </a>\n"
		+ "                                    </div>\n"
		+ "                                </div>\n"
		+ "                                <dl class=\"item_subinfo\">\n"
		+ "                                    <dt class=\"screen_out\">회사정보</dt>\n"
		+ "                                    <dd>카카오</dd>\n"
		+ "                                </dl>\n"
		+ "                                <dl class=\"item_subinfo\">\n"
		+ "                                    <dt class=\"screen_out\">직원유형</dt>\n"
		+ "                                    <dd>정규직</dd>\n"
		+ "                                </dl>\n"
		+ "                            </div>\n"
		+ "                        </li>\n"
		+ "                        <li >\n"
		+ "                            <div class=\"area_info\">\n"
		+ "                                <div class=\"wrap_info\">\n"
		+ "                                    <a href=\"/jobs/S-1681?part=TECHNOLOGY&page=1&company=ALL\" class=\"link_jobs\">\n"
		+ "                                        <h4 class=\"tit_jobs\">[괸계사] 카카오페이 비즈니스 데이터 분석가 (Business Data Analyst) 모집</h4>\n"
		+ "                                    </a>\n"
		+ "                                    <dl class=\"list_info\">\n"
		+ "                                        <dt class=\"screen_out\">영입마감일</dt>\n"
		+ "                                        <dd>영입종료시</dd>\n"
		+ "                                    </dl>\n"
		+ "                                </div>\n"
		+ "                                <dl class=\"item_subinfo\">\n"
		+ "                                    <dt class=\"screen_out\">회사정보</dt>\n"
		+ "                                    <dd>카카오페이</dd>\n"
		+ "                                </dl>\n"
		+ "                                <dl class=\"item_subinfo\">\n"
		+ "                                    <dt class=\"screen_out\">직원유형</dt>\n"
		+ "                                    <dd>정규직</dd>\n"
		+ "                                </dl>\n"
		+ "                            </div>\n"
		+ "                        </li>\n"
		+ "                        <li >\n"
		+ "                            <div class=\"area_info\">\n"
		+ "                                <div class=\"wrap_info\">\n"
		+ "                                    <a href=\"/jobs/S-1679?part=TECHNOLOGY&page=1&company=ALL\" class=\"link_jobs\">\n"
		+ "                                        <h4 class=\"tit_jobs\">[관계사] 카카오페이 정보보호 담당자 모집</h4>\n"
		+ "                                    </a>\n"
		+ "                                    <dl class=\"list_info\">\n"
		+ "                                        <dt class=\"screen_out\">영입마감일</dt>\n"
		+ "                                        <dd>영입종료시</dd>\n"
		+ "                                    </dl>\n"
		+ "                                </div>\n"
		+ "                                <dl class=\"item_subinfo\">\n"
		+ "                                    <dt class=\"screen_out\">회사정보</dt>\n"
		+ "                                    <dd>카카오페이</dd>\n"
		+ "                                </dl>\n"
		+ "                                <dl class=\"item_subinfo\">\n"
		+ "                                    <dt class=\"screen_out\">직원유형</dt>\n"
		+ "                                    <dd>정규직</dd>\n"
		+ "                                </dl>\n"
		+ "                            </div>\n"
		+ "                        </li>\n"
		+ "                        <li >\n"
		+ "                            <div class=\"area_info\">\n"
		+ "                                <div class=\"wrap_info\">\n"
		+ "                                    <a href=\"/jobs/P-11081?part=TECHNOLOGY&page=1&company=ALL\" class=\"link_jobs\">\n"
		+ "                                        <h4 class=\"tit_jobs\">카카오톡/계정/멜론플랫폼 서버 개발자 모집 공고</h4>\n"
		+ "                                    </a>\n"
		+ "                                    <dl class=\"list_info\">\n"
		+ "                                        <dt class=\"screen_out\">영입마감일</dt>\n"
		+ "                                        <dd>영입종료시</dd>\n"
		+ "                                        <dt class=\"screen_out\">근무지</dt>\n"
		+ "                                        <dd>판교</dd>\n"
		+ "                                    </dl>\n"
		+ "                                    <div class=\"list_tag wrap_tag\">\n"
		+ "                                        <strong class=\"screen_out\">직군 태그</strong>\n"
		+ "                                        <a href=\"javascript:void(0);\" data-code=\"Server\" class=\"link_tag\">\n"
		+ "                                            <span class=\"txt_hash\">#</span>Server\n"
		+ "                                        </a>\n"
		+ "                                    </div>\n"
		+ "                                </div>\n"
		+ "                                <dl class=\"item_subinfo\">\n"
		+ "                                    <dt class=\"screen_out\">회사정보</dt>\n"
		+ "                                    <dd>카카오</dd>\n"
		+ "                                </dl>\n"
		+ "                                <dl class=\"item_subinfo\">\n"
		+ "                                    <dt class=\"screen_out\">직원유형</dt>\n"
		+ "                                    <dd>정규직</dd>\n"
		+ "                                </dl>\n"
		+ "                            </div>\n"
		+ "                        </li>\n"
		+ "                        <li >\n"
		+ "                            <div class=\"area_info\">\n"
		+ "                                <div class=\"wrap_info\">\n"
		+ "                                    <a href=\"/jobs/P-11745?part=TECHNOLOGY&page=1&company=ALL\" class=\"link_jobs\">\n"
		+ "                                        <h4 class=\"tit_jobs\">카카오 서비스 클라이언트 Windows 개발자 모집 (경력)</h4>\n"
		+ "                                    </a>\n"
		+ "                                    <dl class=\"list_info\">\n"
		+ "                                        <dt class=\"screen_out\">영입마감일</dt>\n"
		+ "                                        <dd>영입종료시</dd>\n"
		+ "                                        <dt class=\"screen_out\">근무지</dt>\n"
		+ "                                        <dd>판교</dd>\n"
		+ "                                    </dl>\n"
		+ "                                    <div class=\"list_tag wrap_tag\">\n"
		+ "                                        <strong class=\"screen_out\">직군 태그</strong>\n"
		+ "                                        <a href=\"javascript:void(0);\" data-code=\"Windows\" class=\"link_tag\">\n"
		+ "                                            <span class=\"txt_hash\">#</span>Windows\n"
		+ "                                        </a>\n"
		+ "                                    </div>\n"
		+ "                                </div>\n"
		+ "                                <dl class=\"item_subinfo\">\n"
		+ "                                    <dt class=\"screen_out\">회사정보</dt>\n"
		+ "                                    <dd>카카오</dd>\n"
		+ "                                </dl>\n"
		+ "                                <dl class=\"item_subinfo\">\n"
		+ "                                    <dt class=\"screen_out\">직원유형</dt>\n"
		+ "                                    <dd>정규직</dd>\n"
		+ "                                </dl>\n"
		+ "                            </div>\n"
		+ "                        </li>\n"
		+ "                        <li >\n"
		+ "                            <div class=\"area_info\">\n"
		+ "                                <div class=\"wrap_info\">\n"
		+ "                                    <a href=\"/jobs/P-10142?part=TECHNOLOGY&page=1&company=ALL\" class=\"link_jobs\">\n"
		+ "                                        <h4 class=\"tit_jobs\">데이터 사이언스 전문가 및 머신러닝 전문가 모집</h4>\n"
		+ "                                    </a>\n"
		+ "                                    <dl class=\"list_info\">\n"
		+ "                                        <dt class=\"screen_out\">영입마감일</dt>\n"
		+ "                                        <dd>영입종료시</dd>\n"
		+ "                                        <dt class=\"screen_out\">근무지</dt>\n"
		+ "                                        <dd>판교</dd>\n"
		+ "                                    </dl>\n"
		+ "                                    <div class=\"list_tag wrap_tag\">\n"
		+ "                                        <strong class=\"screen_out\">직군 태그</strong>\n"
		+ "                                        <a href=\"javascript:void(0);\" data-code=\"Algorithm_ML\" class=\"link_tag\">\n"
		+ "                                            <span class=\"txt_hash\">#</span>Algorithm/ML\n"
		+ "                                        </a>\n"
		+ "                                        <a href=\"javascript:void(0);\" data-code=\"Algorithm_Ranking\" class=\"link_tag\">\n"
		+ "                                            <span class=\"txt_hash\">#</span>Algorithm/Ranking\n"
		+ "                                        </a>\n"
		+ "                                        <a href=\"javascript:void(0);\" data-code=\"Statistics_Analysis\" class=\"link_tag\">\n"
		+ "                                            <span class=\"txt_hash\">#</span>Statistics/Analysis\n"
		+ "                                        </a>\n"
		+ "                                    </div>\n"
		+ "                                </div>\n"
		+ "                                <dl class=\"item_subinfo\">\n"
		+ "                                    <dt class=\"screen_out\">회사정보</dt>\n"
		+ "                                    <dd>카카오</dd>\n"
		+ "                                </dl>\n"
		+ "                                <dl class=\"item_subinfo\">\n"
		+ "                                    <dt class=\"screen_out\">직원유형</dt>\n"
		+ "                                    <dd>정규직</dd>\n"
		+ "                                </dl>\n"
		+ "                            </div>\n"
		+ "                        </li>\n"
		+ "                    </ul>\n"
		+ "                    <!-- //2020-04-08 추가 끝 -->\n"
		+ "                    <!-- 페이징 -->\n"
		+ "                    <div class=\"paging_list\">\n"
		+ "                        <!-- jobs, 1, 10, , 12 -->\n"
		+ "\n"
		+ "                        <span class=\"inner_pages\">\n"
		+ "        <a href=\"/jobs?page=1\" class=\"change_page btn_fst\"><span class=\"ico_recruit\">맨앞</span></a>\n"
		+ "                    <a class=\"btn_prev\"><span class=\"ico_recruit\">이전</span></a>\n"
		+ "        \n"
		+ "                                                <span class=\"screen_out\">현재 페이지</span><em class=\"link_page\">1</em>\n"
		+ "                                                            <a href=\"/jobs?page=2\" class=\"change_page link_page\">2</a>\n"
		+ "                                                            <a href=\"/jobs?page=3\" class=\"change_page link_page\">3</a>\n"
		+ "                                                            <a href=\"/jobs?page=4\" class=\"change_page link_page\">4</a>\n"
		+ "                                                            <a href=\"/jobs?page=5\" class=\"change_page link_page\">5</a>\n"
		+ "                                                            <a href=\"/jobs?page=6\" class=\"change_page link_page\">6</a>\n"
		+ "                                                            <a href=\"/jobs?page=7\" class=\"change_page link_page\">7</a>\n"
		+ "                                                            <a href=\"/jobs?page=8\" class=\"change_page link_page\">8</a>\n"
		+ "                                                            <a href=\"/jobs?page=9\" class=\"change_page link_page\">9</a>\n"
		+ "                                                            <a href=\"/jobs?page=10\" class=\"change_page link_page\">10</a>\n"
		+ "                    \n"
		+ "                    <a href=\"/jobs?page=2\" class=\"change_page\"><span class=\"btn_next\"><span class=\"ico_recruit\">다음</span></span></a>\n"
		+ "                    <a href=\"/jobs?page=12\" class=\"change_page btn_lst\"><span class=\"ico_recruit\">맨뒤</span></a>\n"
		+ "        </span>\n"
		+ "                    </div>\n"
		+ "                </div>\n"
		+ "            </div>\n"
		+ "        </div>\n"
		+ "    </div>\n"
		+ "    <!-- // kakaoContent -->\n"
		+ "    \n"
		+ "</div>\n"
		+ "\n"
		+ "\n"
		+ "<!-- // kakaoFoot -->\n"
		+ "</body>\n"
		+ "</html>\n";
}