package com.mino.devjob.recruit.service;

import java.util.function.Function;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.web.reactive.function.client.WebClient;

import com.mino.devjob.recruit.model.Recruit;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import reactor.test.StepVerifier;

@ExtendWith(MockitoExtension.class)
class CrawlCoupangServiceTest {
	@InjectMocks
	private CrawlCoupangService crawlCoupangService;
	@Mock
	private WebClient webClientMock;
	@Mock
	private WebClient.RequestHeadersSpec requestHeadersMock;
	@Mock
	private WebClient.RequestHeadersUriSpec requestHeadersUriMock;
	@Mock
	private WebClient.ResponseSpec responseMock;

	@Test
	void crawl() {
		Mockito.when(webClientMock.get()).thenReturn(requestHeadersUriMock);
		Mockito.when(requestHeadersUriMock.uri(Mockito.any(Function.class))).thenReturn(requestHeadersMock);
		Mockito.when(requestHeadersMock.retrieve()).thenReturn(responseMock);
		Mockito.when(responseMock.bodyToMono(String.class)).thenReturn(Mono.just(str));

		Flux<Recruit> crawl = crawlCoupangService.crawl();

		StepVerifier.create(crawl)
			.expectNextCount(15)
			.verifyComplete();
	}

	private String str = "\n"
		+ "<!DOCTYPE html>\n"
		+ "<html id=\"62822\" lang=\"ko\" class=\"html-page catid-62822 no-js\">\n"
		+ "<body id=\"search\" data-site-geolocation=\"true\" data-location-geoType=\"ipambientonly\" data-geolocation-url=\"/search-jobs/GetSearchRequestGeoLocation\">\n"
		+ "\t<div id=\"page\" class=\"page-wrap\">\n"
		+ "\t<main id=\"content\">\n"
		+ "\t\t\n"
		+ "\n"
		+ "<div class=\"wrapper\">\n"
		+ "    <div class=\"container container--flex container--with-aside\">\n"
		+ "        <aside class=\"aside-wrap\">\n"
		+ "                       \n"
		+ "\n"
		+ "    <section id=\"search-filters\" tabindex=\"0\" data-admin-expand=\"true\" data-search-filters-module-name=\"Search Filters\" data-selector-name=\"searchfilters\" data-radius-unit-type=\"0\" data-filtered-categories=\"\" data-filtered-locations=\"\" data-filtered-custom-facet=\"\" data-filtered-advanced-categories=\"\" data-filtered-advanced-locations=\"\" data-filtered-advanced-custom-facet=\"\" data-ajax-char-limit=\"4096\" class=\"\">\n"
		+ "        <div>\n"
		+ "            <h2 class=\"filter-title\">&#xC870;&#xAC74; &#xBCC4; &#xAC80;&#xC0C9;</h2>\n"
		+ "                <div class=\"filter-wrap\">\n"
		+ "                \n"
		+ "                \n"
		+ "                    <section class=\"expandable\" data-expandable=\"true\" data-speed=\"0\" data-enabled=\"true\" data-filter-id=\"5\">\n"
		+ "                        <a href=\"#\" class=\"filter-text expandable-parent \" id=\"job_level-toggle\">&#xC9C1;&#xAD70;</a>\n"
		+ "                        <ul class=\"search-filter-list \" aria-hidden=\"false\" aria-expanded=\"true\">\n"
		+ "                                <li>\n"
		+ "                                    <input type=\"checkbox\" id=\"job_level-filter-0\" class=\"filter-checkbox\" data-facet-type=\"5\" data-id=\"Technology\" data-count=\"45\" data-display=\"Technology\" data-field-name=\"job_level\" />\n"
		+ "                                    <label class=\"filter-label\" for=\"job_level-filter-0\"><strong class=\"filter\">Technology</strong> <strong>45</strong></label>\n"
		+ "                                </li>\n"
		+ "                        </ul>\n"
		+ "                    </section>\n"
		+ "                    <section class=\"expandable\" data-expandable=\"true\" data-speed=\"0\" data-enabled=\"true\" data-filter-id=\"5\">\n"
		+ "                        <a href=\"#\" class=\"filter-text expandable-parent \" id=\"job_type-toggle\">Mission Teams</a>\n"
		+ "                        <ul class=\"search-filter-list \" aria-hidden=\"false\" aria-expanded=\"true\">\n"
		+ "                                <li>\n"
		+ "                                    <input type=\"checkbox\" id=\"job_type-filter-0\" class=\"filter-checkbox\" data-facet-type=\"5\" data-id=\"eCommerce\" data-count=\"17\" data-display=\"eCommerce\" data-field-name=\"job_type\" />\n"
		+ "                                    <label class=\"filter-label\" for=\"job_type-filter-0\"><strong class=\"filter\">eCommerce</strong> <strong>17</strong></label>\n"
		+ "                                </li>\n"
		+ "                                <li>\n"
		+ "                                    <input type=\"checkbox\" id=\"job_type-filter-1\" class=\"filter-checkbox\" data-facet-type=\"5\" data-id=\"Fulfilment Services\" data-count=\"5\" data-display=\"Fulfilment Services\" data-field-name=\"job_type\" />\n"
		+ "                                    <label class=\"filter-label\" for=\"job_type-filter-1\"><strong class=\"filter\">Fulfilment Services</strong> <strong>5</strong></label>\n"
		+ "                                </li>\n"
		+ "                                <li>\n"
		+ "                                    <input type=\"checkbox\" id=\"job_type-filter-2\" class=\"filter-checkbox\" data-facet-type=\"5\" data-id=\"Logistics Services\" data-count=\"3\" data-display=\"Logistics Services\" data-field-name=\"job_type\" />\n"
		+ "                                    <label class=\"filter-label\" for=\"job_type-filter-2\"><strong class=\"filter\">Logistics Services</strong> <strong>3</strong></label>\n"
		+ "                                </li>\n"
		+ "                                <li>\n"
		+ "                                    <input type=\"checkbox\" id=\"job_type-filter-3\" class=\"filter-checkbox\" data-facet-type=\"5\" data-id=\"Platform, Search and Discovery\" data-count=\"18\" data-display=\"Platform, Search and Discovery\" data-field-name=\"job_type\" />\n"
		+ "                                    <label class=\"filter-label\" for=\"job_type-filter-3\"><strong class=\"filter\">Platform, Search and Discovery</strong> <strong>18</strong></label>\n"
		+ "                                </li>\n"
		+ "                                <li>\n"
		+ "                                    <input type=\"checkbox\" id=\"job_type-filter-4\" class=\"filter-checkbox\" data-facet-type=\"5\" data-id=\"Security, Privacy and Technology Infrastructure\" data-count=\"2\" data-display=\"Security, Privacy and Technology Infrastructure\" data-field-name=\"job_type\" />\n"
		+ "                                    <label class=\"filter-label\" for=\"job_type-filter-4\"><strong class=\"filter\">Security, Privacy and Technology Infrastructure</strong> <strong>2</strong></label>\n"
		+ "                                </li>\n"
		+ "                        </ul>\n"
		+ "                    </section>\n"
		+ "    \n"
		+ "                    <section class=\"expandable\" data-expandable=\"true\" data-speed=\"0\" data-enabled=\"true\" data-filter-id=\"1\">\n"
		+ "                        <a href=\"#\" class=\"expandable-parent filter-text \" id=\"category-toggle\">&#xC9C1;&#xBB34;</a>\n"
		+ "                        <ul class=\"search-filter-list  \" aria-hidden=\"false\" aria-expanded=\"true\">\n"
		+ "                                <li >\n"
		+ "                                        <input type=\"checkbox\" id=\"category-filter-0\" class=\"filter-checkbox\" data-facet-type=\"1\" data-id=\"63827\" data-count=\"5\" data-display=\"Audit\" data-field-name=\"\" />\n"
		+ "                                        <label class=\"filter-label\" for=\"category-filter-0\"><strong class=\"filter\">Audit</strong> <strong>5</strong></label>\n"
		+ "    \n"
		+ "    \n"
		+ "                                </li>\n"
		+ "                                <li >\n"
		+ "                                        <input type=\"checkbox\" id=\"category-filter-1\" class=\"filter-checkbox\" data-facet-type=\"1\" data-id=\"62773\" data-count=\"34\" data-display=\"Business Planning\" data-field-name=\"\" />\n"
		+ "                                        <label class=\"filter-label\" for=\"category-filter-1\"><strong class=\"filter\">Business Planning</strong> <strong>34</strong></label>\n"
		+ "    \n"
		+ "    \n"
		+ "                                </li>\n"
		+ "                                <li >\n"
		+ "                                        <input type=\"checkbox\" id=\"category-filter-2\" class=\"filter-checkbox\" data-facet-type=\"1\" data-id=\"62774\" data-count=\"13\" data-display=\"Business Support Service\" data-field-name=\"\" />\n"
		+ "                                        <label class=\"filter-label\" for=\"category-filter-2\"><strong class=\"filter\">Business Support Service</strong> <strong>13</strong></label>\n"
		+ "    \n"
		+ "    \n"
		+ "                                </li>\n"
		+ "                                <li >\n"
		+ "                                        <input type=\"checkbox\" id=\"category-filter-3\" class=\"filter-checkbox\" data-facet-type=\"1\" data-id=\"63828\" data-count=\"5\" data-display=\"Contents UX\" data-field-name=\"\" />\n"
		+ "                                        <label class=\"filter-label\" for=\"category-filter-3\"><strong class=\"filter\">Contents UX</strong> <strong>5</strong></label>\n"
		+ "    \n"
		+ "    \n"
		+ "                                </li>\n"
		+ "                                <li >\n"
		+ "                                        <input type=\"checkbox\" id=\"category-filter-4\" class=\"filter-checkbox\" data-facet-type=\"1\" data-id=\"62916\" data-count=\"2\" data-display=\"Customer Services\" data-field-name=\"\" />\n"
		+ "                                        <label class=\"filter-label\" for=\"category-filter-4\"><strong class=\"filter\">Customer Services</strong> <strong>2</strong></label>\n"
		+ "    \n"
		+ "    \n"
		+ "                                </li>\n"
		+ "                                <li >\n"
		+ "                                        <input type=\"checkbox\" id=\"category-filter-5\" class=\"filter-checkbox\" data-facet-type=\"1\" data-id=\"62812\" data-count=\"6\" data-display=\"Data Engineering\" data-field-name=\"\" />\n"
		+ "                                        <label class=\"filter-label\" for=\"category-filter-5\"><strong class=\"filter\">Data Engineering</strong> <strong>6</strong></label>\n"
		+ "    \n"
		+ "    \n"
		+ "                                </li>\n"
		+ "                                <li >\n"
		+ "                                        <input type=\"checkbox\" id=\"category-filter-6\" class=\"filter-checkbox\" data-facet-type=\"1\" data-id=\"63872\" data-count=\"7\" data-display=\"Delivery Support\" data-field-name=\"\" />\n"
		+ "                                        <label class=\"filter-label\" for=\"category-filter-6\"><strong class=\"filter\">Delivery Support</strong> <strong>7</strong></label>\n"
		+ "    \n"
		+ "    \n"
		+ "                                </li>\n"
		+ "                                <li >\n"
		+ "                                        <input type=\"checkbox\" id=\"category-filter-7\" class=\"filter-checkbox\" data-facet-type=\"1\" data-id=\"63523\" data-count=\"4\" data-display=\"E-Commerce Operations\" data-field-name=\"\" />\n"
		+ "                                        <label class=\"filter-label\" for=\"category-filter-7\"><strong class=\"filter\">E-Commerce Operations</strong> <strong>4</strong></label>\n"
		+ "    \n"
		+ "    \n"
		+ "                                </li>\n"
		+ "                                <li >\n"
		+ "                                        <input type=\"checkbox\" id=\"category-filter-8\" class=\"filter-checkbox\" data-facet-type=\"1\" data-id=\"62824\" data-count=\"14\" data-display=\"FC Support\" data-field-name=\"\" />\n"
		+ "                                        <label class=\"filter-label\" for=\"category-filter-8\"><strong class=\"filter\">FC Support</strong> <strong>14</strong></label>\n"
		+ "    \n"
		+ "    \n"
		+ "                                </li>\n"
		+ "                                <li >\n"
		+ "                                        <input type=\"checkbox\" id=\"category-filter-9\" class=\"filter-checkbox\" data-facet-type=\"1\" data-id=\"62273\" data-count=\"21\" data-display=\"Finance\" data-field-name=\"\" />\n"
		+ "                                        <label class=\"filter-label\" for=\"category-filter-9\"><strong class=\"filter\">Finance</strong> <strong>21</strong></label>\n"
		+ "    \n"
		+ "    \n"
		+ "                                </li>\n"
		+ "                                <li >\n"
		+ "                                        <input type=\"checkbox\" id=\"category-filter-10\" class=\"filter-checkbox\" data-facet-type=\"1\" data-id=\"62813\" data-count=\"4\" data-display=\"FinTech Business\" data-field-name=\"\" />\n"
		+ "                                        <label class=\"filter-label\" for=\"category-filter-10\"><strong class=\"filter\">FinTech Business</strong> <strong>4</strong></label>\n"
		+ "    \n"
		+ "    \n"
		+ "                                </li>\n"
		+ "                                <li >\n"
		+ "                                        <input type=\"checkbox\" id=\"category-filter-11\" class=\"filter-checkbox\" data-facet-type=\"1\" data-id=\"62775\" data-count=\"56\" data-display=\"HR\" data-field-name=\"\" />\n"
		+ "                                        <label class=\"filter-label\" for=\"category-filter-11\"><strong class=\"filter\">HR</strong> <strong>56</strong></label>\n"
		+ "    \n"
		+ "    \n"
		+ "                                </li>\n"
		+ "                                <li >\n"
		+ "                                        <input type=\"checkbox\" id=\"category-filter-12\" class=\"filter-checkbox\" data-facet-type=\"1\" data-id=\"62815\" data-count=\"17\" data-display=\"Infra Engineering\" data-field-name=\"\" />\n"
		+ "                                        <label class=\"filter-label\" for=\"category-filter-12\"><strong class=\"filter\">Infra Engineering</strong> <strong>17</strong></label>\n"
		+ "    \n"
		+ "    \n"
		+ "                                </li>\n"
		+ "                                <li >\n"
		+ "                                        <input type=\"checkbox\" id=\"category-filter-13\" class=\"filter-checkbox\" data-facet-type=\"1\" data-id=\"63829\" data-count=\"20\" data-display=\"Legal\" data-field-name=\"\" />\n"
		+ "                                        <label class=\"filter-label\" for=\"category-filter-13\"><strong class=\"filter\">Legal</strong> <strong>20</strong></label>\n"
		+ "    \n"
		+ "    \n"
		+ "                                </li>\n"
		+ "                                <li >\n"
		+ "                                        <input type=\"checkbox\" id=\"category-filter-14\" class=\"filter-checkbox\" data-facet-type=\"1\" data-id=\"62816\" data-count=\"20\" data-display=\"Logistics Planning\" data-field-name=\"\" />\n"
		+ "                                        <label class=\"filter-label\" for=\"category-filter-14\"><strong class=\"filter\">Logistics Planning</strong> <strong>20</strong></label>\n"
		+ "    \n"
		+ "    \n"
		+ "                                </li>\n"
		+ "                                <li >\n"
		+ "                                        <input type=\"checkbox\" id=\"category-filter-15\" class=\"filter-checkbox\" data-facet-type=\"1\" data-id=\"62814\" data-count=\"7\" data-display=\"Marketing & Advertising\" data-field-name=\"\" />\n"
		+ "                                        <label class=\"filter-label\" for=\"category-filter-15\"><strong class=\"filter\">Marketing &amp; Advertising</strong> <strong>7</strong></label>\n"
		+ "    \n"
		+ "    \n"
		+ "                                </li>\n"
		+ "                                <li >\n"
		+ "                                        <input type=\"checkbox\" id=\"category-filter-16\" class=\"filter-checkbox\" data-facet-type=\"1\" data-id=\"62817\" data-count=\"3\" data-display=\"Merchandising Support\" data-field-name=\"\" />\n"
		+ "                                        <label class=\"filter-label\" for=\"category-filter-16\"><strong class=\"filter\">Merchandising Support</strong> <strong>3</strong></label>\n"
		+ "    \n"
		+ "    \n"
		+ "                                </li>\n"
		+ "                                <li >\n"
		+ "                                        <input type=\"checkbox\" id=\"category-filter-17\" class=\"filter-checkbox\" data-facet-type=\"1\" data-id=\"62776\" data-count=\"7\" data-display=\"Product Management\" data-field-name=\"\" />\n"
		+ "                                        <label class=\"filter-label\" for=\"category-filter-17\"><strong class=\"filter\">Product Management</strong> <strong>7</strong></label>\n"
		+ "    \n"
		+ "    \n"
		+ "                                </li>\n"
		+ "                                <li >\n"
		+ "                                        <input type=\"checkbox\" id=\"category-filter-18\" class=\"filter-checkbox\" data-facet-type=\"1\" data-id=\"62818\" data-count=\"9\" data-display=\"Retail\" data-field-name=\"\" />\n"
		+ "                                        <label class=\"filter-label\" for=\"category-filter-18\"><strong class=\"filter\">Retail</strong> <strong>9</strong></label>\n"
		+ "    \n"
		+ "    \n"
		+ "                                </li>\n"
		+ "                                <li >\n"
		+ "                                        <input type=\"checkbox\" id=\"category-filter-19\" class=\"filter-checkbox\" data-facet-type=\"1\" data-id=\"62819\" data-count=\"14\" data-display=\"Sales and Account Management\" data-field-name=\"\" />\n"
		+ "                                        <label class=\"filter-label\" for=\"category-filter-19\"><strong class=\"filter\">Sales and Account Management</strong> <strong>14</strong></label>\n"
		+ "    \n"
		+ "    \n"
		+ "                                </li>\n"
		+ "                                <li >\n"
		+ "                                        <input type=\"checkbox\" id=\"category-filter-20\" class=\"filter-checkbox\" data-facet-type=\"1\" data-id=\"63831\" data-count=\"5\" data-display=\"SCM\" data-field-name=\"\" />\n"
		+ "                                        <label class=\"filter-label\" for=\"category-filter-20\"><strong class=\"filter\">SCM</strong> <strong>5</strong></label>\n"
		+ "    \n"
		+ "    \n"
		+ "                                </li>\n"
		+ "                                <li >\n"
		+ "                                        <input type=\"checkbox\" id=\"category-filter-21\" class=\"filter-checkbox\" data-facet-type=\"1\" data-id=\"62820\" data-count=\"25\" data-display=\"Security Technology\" data-field-name=\"\" />\n"
		+ "                                        <label class=\"filter-label\" for=\"category-filter-21\"><strong class=\"filter\">Security Technology</strong> <strong>25</strong></label>\n"
		+ "    \n"
		+ "    \n"
		+ "                                </li>\n"
		+ "                                <li >\n"
		+ "                                        <input type=\"checkbox\" id=\"category-filter-22\" class=\"filter-checkbox\" data-facet-type=\"1\" data-id=\"62822\" data-count=\"45\" data-display=\"Software Development Engineers\" data-field-name=\"\" checked=\"checked\" />\n"
		+ "                                        <label class=\"filter-label\" for=\"category-filter-22\"><strong class=\"filter\">Software Development Engineers</strong> <strong>45</strong></label>\n"
		+ "    \n"
		+ "    \n"
		+ "                                </li>\n"
		+ "                                <li >\n"
		+ "                                        <input type=\"checkbox\" id=\"category-filter-23\" class=\"filter-checkbox\" data-facet-type=\"1\" data-id=\"62777\" data-count=\"4\" data-display=\"Tech Management\" data-field-name=\"\" />\n"
		+ "                                        <label class=\"filter-label\" for=\"category-filter-23\"><strong class=\"filter\">Tech Management</strong> <strong>4</strong></label>\n"
		+ "    \n"
		+ "    \n"
		+ "                                </li>\n"
		+ "                                <li >\n"
		+ "                                        <input type=\"checkbox\" id=\"category-filter-24\" class=\"filter-checkbox\" data-facet-type=\"1\" data-id=\"62778\" data-count=\"16\" data-display=\"UX\" data-field-name=\"\" />\n"
		+ "                                        <label class=\"filter-label\" for=\"category-filter-24\"><strong class=\"filter\">UX</strong> <strong>16</strong></label>\n"
		+ "    \n"
		+ "    \n"
		+ "                                </li>\n"
		+ "                        </ul>\n"
		+ "                    </section>\n"
		+ "    \n"
		+ "                    <section class=\"expandable\" data-expandable=\"true\" data-speed=\"0\" data-enabled=\"true\" data-filter-id=\"2\">\n"
		+ "                        <a href=\"#\" class=\"expandable-parent filter-text \" id=\"country-toggle\">&#xAD6D;&#xAC00;</a>\n"
		+ "                        <ul class=\"search-filter-list \" aria-hidden=\"false\" aria-expanded=\"true\">\n"
		+ "                                <li>\n"
		+ "                                    <input type=\"checkbox\" id=\"country-filter-0\" class=\"filter-checkbox\" data-facet-type=\"2\" data-id=\"1835841\" data-count=\"45\" data-display=\"대한민국\" data-field-name=\"\" checked=\"checked\" />\n"
		+ "                                    <label class=\"filter-label\" for=\"country-filter-0\"><strong class=\"filter\">&#xB300;&#xD55C;&#xBBFC;&#xAD6D;</strong> <strong>45</strong></label>\n"
		+ "                                </li>\n"
		+ "                                <li>\n"
		+ "                                    <input type=\"checkbox\" id=\"country-filter-1\" class=\"filter-checkbox\" data-facet-type=\"2\" data-id=\"6252001\" data-count=\"28\" data-display=\"미국\" data-field-name=\"\" />\n"
		+ "                                    <label class=\"filter-label\" for=\"country-filter-1\"><strong class=\"filter\">&#xBBF8;&#xAD6D;</strong> <strong>28</strong></label>\n"
		+ "                                </li>\n"
		+ "                                <li>\n"
		+ "                                    <input type=\"checkbox\" id=\"country-filter-2\" class=\"filter-checkbox\" data-facet-type=\"2\" data-id=\"1814991\" data-count=\"34\" data-display=\"중국\" data-field-name=\"\" />\n"
		+ "                                    <label class=\"filter-label\" for=\"country-filter-2\"><strong class=\"filter\">&#xC911;&#xAD6D;</strong> <strong>34</strong></label>\n"
		+ "                                </li>\n"
		+ "                        </ul>\n"
		+ "                    </section>\n"
		+ "    \n"
		+ "                    <section class=\"expandable\" data-expandable=\"true\" data-speed=\"0\" data-enabled=\"false\" data-filter-id=\"3\">\n"
		+ "                        <a href=\"#\" class=\"expandable-parent filter-text \" id=\"region-toggle\">State</a>\n"
		+ "                        <ul class=\"search-filter-list \" aria-hidden=\"false\" aria-expanded=\"true\">\n"
		+ "                                <li>\n"
		+ "                                    <input type=\"checkbox\" id=\"region-filter-0\" class=\"filter-checkbox\" data-facet-type=\"3\" data-id=\"1835841-1835847\" data-count=\"45\" data-display=\"서울특별시, 대한민국\" data-field-name=\"\" />\n"
		+ "                                    <label class=\"filter-label\" for=\"region-filter-0\"><strong class=\"filter\">&#xC11C;&#xC6B8;&#xD2B9;&#xBCC4;&#xC2DC;</strong> <strong>45</strong></label>\n"
		+ "                                </li>\n"
		+ "                        </ul>\n"
		+ "                    </section>\n"
		+ "                    <section class=\"expandable\" data-expandable=\"true\" data-speed=\"0\" data-enabled=\"true\" data-filter-id=\"4\">\n"
		+ "                        <a href=\"#\" class=\"expandable-parent filter-text \" id=\"city-toggle\">&#xB3C4;&#xC2DC;</a>\n"
		+ "                        <ul class=\"search-filter-list \" aria-hidden=\"false\" aria-expanded=\"true\">\n"
		+ "                                <li>\n"
		+ "                                    <input type=\"checkbox\" id=\"city-filter-0\" class=\"filter-checkbox\" data-facet-type=\"4\" data-id=\"1835841-1835847-1835848\" data-count=\"45\" data-display=\"서울, 서울특별시, 대한민국\" data-field-name=\"\" />\n"
		+ "                                    <label class=\"filter-label\" for=\"city-filter-0\"><strong class=\"filter\">&#xC11C;&#xC6B8;</strong> <strong>45</strong></label>\n"
		+ "                                </li>\n"
		+ "                        </ul>\n"
		+ "                    </section>\n"
		+ "    \n"
		+ "                    <section class=\"expandable\" data-expandable=\"true\" data-speed=\"0\" data-enabled=\"false\" data-filter-id=\"6\">\n"
		+ "                        <a href=\"#\" class=\"expandable-parent filter-text \" id=\"companydivision-toggle\">Divisions</a>\n"
		+ "                        <ul class=\"search-filter-list \" aria-hidden=\"false\" aria-expanded=\"true\">\n"
		+ "                                <li>\n"
		+ "                                    <input type=\"checkbox\" id=\"companydivision-filter-0\" class=\"filter-checkbox\" data-facet-type=\"6\" data-id=\"24450\" data-count=\"45\" data-display=\"Coupang Korean\" data-field-name=\"\"/>\n"
		+ "                                    <label class=\"filter-label\" for=\"companydivision-filter-0\"><strong class=\"filter\">Coupang Korean</strong> <strong>45</strong></label>\n"
		+ "                                </li>\n"
		+ "                        </ul>\n"
		+ "                    </section>\n"
		+ "    \n"
		+ "                \n"
		+ "            </div>\n"
		+ "            <div id=\"search-filter-controls\" class=\"submit job-alert-submit\">\n"
		+ "                <div class=\"button-slant input-button\">\n"
		+ "                    <div class=\"button-border\"></div>\n"
		+ "                    <div class=\"button-border button-bottom\"></div>\n"
		+ "                    <div class=\"button-contents\"><span><input id=\"search-filter-clear\" type=\"submit\" value=\"&#xC804;&#xCCB4; &#xD574;&#xC81C;\"></span></div>\n"
		+ "                     \n"
		+ "                </div> \n"
		+ "            </div>\n"
		+ "        </div>\n"
		+ "    </section>\n"
		+ "\n"
		+ "\n"
		+ "\n"
		+ "    <section class=\"recently-viewed-job-list\" data-recently-viewed-jobs=\"false\" data-company-site-id=\"12764\" data-ajax-url=\"//rocketyourcareer.kr.coupang.com/module/postmodule\" data-module-name=\"Previously Viewed Jobs\" data-module-type=\"RecentlyViewedJobList\" data-selector-name=\"recentlyviewedjoblist\" data-content-type=\"Dynamic\">\n"
		+ "    </section>\n"
		+ "\n"
		+ "\n"
		+ "        </aside>\n"
		+ "\n"
		+ "\n"
		+ "    <section id=\"search-results\" tabindex=\"0\" data-keywords=\"\" data-location=\"대한민국\" data-distance=\"50\" data-latitude=\"\" data-longitude=\"\" data-show-radius=\"False\" data-total-results=\"45\" data-total-pages=\"3\" data-current-page=\"1\" data-records-per-page=\"15\" data-active-facet-id=\"0\" data-custom-facet-name=\"\" data-facet-term=\"\" data-facet-type=\"0\" data-search-results-module-name=\"Search Results\" data-sort-criteria=\"0\" data-sort-direction=\"0\" data-search-type=\"6\" data-ajax-url=\"/search-jobs/results\" data-ajax-post-url=\"/search-jobs/resultspost\" data-server-error-message=\"요청 결과를 가져오던 중 오류가 발생했습니다. 페이지를 새로 고침하여 재시도해보십시오.\" data-keyword-type=\"\" data-location-type=\"\" data-location-path=\"\" data-organization-ids=\"24450\" data-selector-name=\"searchresults\" data-refined-keywords=\"[]\" data-postal-code=\"\" data-save-jobs=\"true\" data-use-noindex=\"true\">\n"
		+ "        <h2 class=\"result-count\">\n"
		+ "            <span class=\"result-count-number\">15</span> \n"
		+ "            <span class=\"result-count-text\">Results Found</span>\n"
		+ "        </h2>\n"
		+ "        \n"
		+ "        <h1 role=\"status\"></h1>\n"
		+ "\n"
		+ "            <section id=\"search-results-list\">\n"
		+ "                \n"
		+ "\t                <div id=\"applied-filters\" class=\"search-results-options\">\n"
		+ "                        <h2 class=\"applied-filters-label\" id=\"applied-filters-label\">&#xAC80;&#xC0C9; &#xC870;&#xAC74;</h2>\n"
		+ "\t\t\t\t\t\t<ul aria-labelledby=\"applied-filters-label\" tabindex=\"0\" role=\"presentation\" class=\"search-results-tags\">\n"
		+ "                                                    <li><a class=\"filter-button\" href=\"#\" data-id=\"62822\" data-facet-type=\"1\">Software Development Engineers</a></li>\n"
		+ "                                                    <li><a class=\"filter-button\" href=\"#\" data-id=\"1835841\" data-facet-type=\"2\">&#xB300;&#xD55C;&#xBBFC;&#xAD6D;</a></li>\n"
		+ "\t\t\t\t\t\t</ul>\n"
		+ "\t                </div>\n"
		+ "\n"
		+ "\n"
		+ "                <ul class=\"searched-job-list\">\n"
		+ "                        <li class=\"searched-job-item\">\n"
		+ "                            <a href=\"/%ec%a7%81%eb%ac%b4/-/coupang-pay-sr-manager-back-end-engineering-platform/24450/17221795\" data-job-id=\"17221795\">\n"
		+ "                                <h3 class=\"searched-job-title\">[Coupang Pay] Sr. Manager, Back-end Engineering (Platform)</h3>\n"
		+ "                                    <span class=\"searched-job-location\">&#xC11C;&#xC6B8;,  &#xB300;&#xD55C;&#xBBFC;&#xAD6D;</span>\n"
		+ "            \n"
		+ "                            </a>\n"
		+ "                            <div class=\"job-detail-buttons search-result-detail-buttons\">\n"
		+ "                                    <button type=\"button\" aria-label=\"Save Job\" class=\"js-save-job-btn\" data-job-id=\"17221795\" data-org-id=\"24450\"></button>\n"
		+ "                            </div>\n"
		+ "                        </li>\n"
		+ "                        <li class=\"searched-job-item\">\n"
		+ "                            <a href=\"/%ec%a7%81%eb%ac%b4/-/principal-back-end-engineering-cmg-tech/24450/17182859\" data-job-id=\"17182859\">\n"
		+ "                                <h3 class=\"searched-job-title\">Principal, Back-end Engineering (CMG Tech)</h3>\n"
		+ "                                    <span class=\"searched-job-location\">&#xC11C;&#xC6B8;,  &#xB300;&#xD55C;&#xBBFC;&#xAD6D;</span>\n"
		+ "            \n"
		+ "                            </a>\n"
		+ "                            <div class=\"job-detail-buttons search-result-detail-buttons\">\n"
		+ "                                    <button type=\"button\" aria-label=\"Save Job\" class=\"js-save-job-btn\" data-job-id=\"17182859\" data-org-id=\"24450\"></button>\n"
		+ "                            </div>\n"
		+ "                        </li>\n"
		+ "                        <li class=\"searched-job-item\">\n"
		+ "                            <a href=\"/%ec%a7%81%eb%ac%b4/-/senior-full-stack-engineer-cmg-tech/24450/17182864\" data-job-id=\"17182864\">\n"
		+ "                                <h3 class=\"searched-job-title\">Senior, Full-stack Engineer (CMG Tech)</h3>\n"
		+ "                                    <span class=\"searched-job-location\">&#xC11C;&#xC6B8;,  &#xB300;&#xD55C;&#xBBFC;&#xAD6D;</span>\n"
		+ "            \n"
		+ "                            </a>\n"
		+ "                            <div class=\"job-detail-buttons search-result-detail-buttons\">\n"
		+ "                                    <button type=\"button\" aria-label=\"Save Job\" class=\"js-save-job-btn\" data-job-id=\"17182864\" data-org-id=\"24450\"></button>\n"
		+ "                            </div>\n"
		+ "                        </li>\n"
		+ "                        <li class=\"searched-job-item\">\n"
		+ "                            <a href=\"/%ec%a7%81%eb%ac%b4/-/senior-software-development-manager-iap/24450/17156063\" data-job-id=\"17156063\">\n"
		+ "                                <h3 class=\"searched-job-title\">Senior Software Development Manager (IAP)</h3>\n"
		+ "                                    <span class=\"searched-job-location\">&#xC11C;&#xC6B8;,  &#xB300;&#xD55C;&#xBBFC;&#xAD6D;</span>\n"
		+ "            \n"
		+ "                            </a>\n"
		+ "                            <div class=\"job-detail-buttons search-result-detail-buttons\">\n"
		+ "                                    <button type=\"button\" aria-label=\"Save Job\" class=\"js-save-job-btn\" data-job-id=\"17156063\" data-org-id=\"24450\"></button>\n"
		+ "                            </div>\n"
		+ "                        </li>\n"
		+ "                        <li class=\"searched-job-item\">\n"
		+ "                            <a href=\"/%ec%a7%81%eb%ac%b4/-/sr-front-end-engineer-wms-front/24450/17153905\" data-job-id=\"17153905\">\n"
		+ "                                <h3 class=\"searched-job-title\">Sr. Front-end Engineer (WMS Front)</h3>\n"
		+ "                                    <span class=\"searched-job-location\">&#xC11C;&#xC6B8;,  &#xB300;&#xD55C;&#xBBFC;&#xAD6D;</span>\n"
		+ "            \n"
		+ "                            </a>\n"
		+ "                            <div class=\"job-detail-buttons search-result-detail-buttons\">\n"
		+ "                                    <button type=\"button\" aria-label=\"Save Job\" class=\"js-save-job-btn\" data-job-id=\"17153905\" data-org-id=\"24450\"></button>\n"
		+ "                            </div>\n"
		+ "                        </li>\n"
		+ "                        <li class=\"searched-job-item\">\n"
		+ "                            <a href=\"/%ec%a7%81%eb%ac%b4/-/senior-back-end-engineer-return-management-system/24450/17131765\" data-job-id=\"17131765\">\n"
		+ "                                <h3 class=\"searched-job-title\">Senior, Back-end Engineer (Return Management System)</h3>\n"
		+ "                                    <span class=\"searched-job-location\">&#xC11C;&#xC6B8;,  &#xB300;&#xD55C;&#xBBFC;&#xAD6D;</span>\n"
		+ "            \n"
		+ "                            </a>\n"
		+ "                            <div class=\"job-detail-buttons search-result-detail-buttons\">\n"
		+ "                                    <button type=\"button\" aria-label=\"Save Job\" class=\"js-save-job-btn\" data-job-id=\"17131765\" data-org-id=\"24450\"></button>\n"
		+ "                            </div>\n"
		+ "                        </li>\n"
		+ "                        <li class=\"searched-job-item\">\n"
		+ "                            <a href=\"/%ec%a7%81%eb%ac%b4/-/senior-back-end-engineer-cs-intelligence/24450/17131766\" data-job-id=\"17131766\">\n"
		+ "                                <h3 class=\"searched-job-title\">Senior, Back-end Engineer (CS Intelligence)</h3>\n"
		+ "                                    <span class=\"searched-job-location\">&#xC11C;&#xC6B8;,  &#xB300;&#xD55C;&#xBBFC;&#xAD6D;</span>\n"
		+ "            \n"
		+ "                            </a>\n"
		+ "                            <div class=\"job-detail-buttons search-result-detail-buttons\">\n"
		+ "                                    <button type=\"button\" aria-label=\"Save Job\" class=\"js-save-job-btn\" data-job-id=\"17131766\" data-org-id=\"24450\"></button>\n"
		+ "                            </div>\n"
		+ "                        </li>\n"
		+ "                        <li class=\"searched-job-item\">\n"
		+ "                            <a href=\"/%ec%a7%81%eb%ac%b4/-/principal-back-end-engineer-customer-return-platform/24450/17131000\" data-job-id=\"17131000\">\n"
		+ "                                <h3 class=\"searched-job-title\">Principal, Back-end Engineer (Customer Return Platform)</h3>\n"
		+ "                                    <span class=\"searched-job-location\">&#xC11C;&#xC6B8;,  &#xB300;&#xD55C;&#xBBFC;&#xAD6D;</span>\n"
		+ "            \n"
		+ "                            </a>\n"
		+ "                            <div class=\"job-detail-buttons search-result-detail-buttons\">\n"
		+ "                                    <button type=\"button\" aria-label=\"Save Job\" class=\"js-save-job-btn\" data-job-id=\"17131000\" data-org-id=\"24450\"></button>\n"
		+ "                            </div>\n"
		+ "                        </li>\n"
		+ "                        <li class=\"searched-job-item\">\n"
		+ "                            <a href=\"/%ec%a7%81%eb%ac%b4/-/principal-back-end-engineer-cs-intelligence/24450/17131002\" data-job-id=\"17131002\">\n"
		+ "                                <h3 class=\"searched-job-title\">Principal, Back-end Engineer (CS Intelligence)</h3>\n"
		+ "                                    <span class=\"searched-job-location\">&#xC11C;&#xC6B8;,  &#xB300;&#xD55C;&#xBBFC;&#xAD6D;</span>\n"
		+ "            \n"
		+ "                            </a>\n"
		+ "                            <div class=\"job-detail-buttons search-result-detail-buttons\">\n"
		+ "                                    <button type=\"button\" aria-label=\"Save Job\" class=\"js-save-job-btn\" data-job-id=\"17131002\" data-org-id=\"24450\"></button>\n"
		+ "                            </div>\n"
		+ "                        </li>\n"
		+ "                        <li class=\"searched-job-item\">\n"
		+ "                            <a href=\"/%ec%a7%81%eb%ac%b4/-/senior-software-engineer-search-infrastructure/24450/17095026\" data-job-id=\"17095026\">\n"
		+ "                                <h3 class=\"searched-job-title\">Senior, Software Engineer (Search Infrastructure)</h3>\n"
		+ "                                    <span class=\"searched-job-location\">&#xC11C;&#xC6B8;,  &#xB300;&#xD55C;&#xBBFC;&#xAD6D;</span>\n"
		+ "            \n"
		+ "                            </a>\n"
		+ "                            <div class=\"job-detail-buttons search-result-detail-buttons\">\n"
		+ "                                    <button type=\"button\" aria-label=\"Save Job\" class=\"js-save-job-btn\" data-job-id=\"17095026\" data-org-id=\"24450\"></button>\n"
		+ "                            </div>\n"
		+ "                        </li>\n"
		+ "                        <li class=\"searched-job-item\">\n"
		+ "                            <a href=\"/%ec%a7%81%eb%ac%b4/-/sr-manager-android-engineering-mobile-engineering/24450/16933535\" data-job-id=\"16933535\">\n"
		+ "                                <h3 class=\"searched-job-title\">Sr.Manager, Android Engineering (Mobile Engineering)</h3>\n"
		+ "                                    <span class=\"searched-job-location\">&#xC11C;&#xC6B8;,  &#xB300;&#xD55C;&#xBBFC;&#xAD6D;</span>\n"
		+ "            \n"
		+ "                            </a>\n"
		+ "                            <div class=\"job-detail-buttons search-result-detail-buttons\">\n"
		+ "                                    <button type=\"button\" aria-label=\"Save Job\" class=\"js-save-job-btn\" data-job-id=\"16933535\" data-org-id=\"24450\"></button>\n"
		+ "                            </div>\n"
		+ "                        </li>\n"
		+ "                        <li class=\"searched-job-item\">\n"
		+ "                            <a href=\"/%ec%a7%81%eb%ac%b4/-/sr-qa-engineer-product-service/24450/16921064\" data-job-id=\"16921064\">\n"
		+ "                                <h3 class=\"searched-job-title\">Sr. QA Engineer (Product Service)</h3>\n"
		+ "                                    <span class=\"searched-job-location\">&#xC11C;&#xC6B8;,  &#xB300;&#xD55C;&#xBBFC;&#xAD6D;</span>\n"
		+ "            \n"
		+ "                            </a>\n"
		+ "                            <div class=\"job-detail-buttons search-result-detail-buttons\">\n"
		+ "                                    <button type=\"button\" aria-label=\"Save Job\" class=\"js-save-job-btn\" data-job-id=\"16921064\" data-org-id=\"24450\"></button>\n"
		+ "                            </div>\n"
		+ "                        </li>\n"
		+ "                        <li class=\"searched-job-item\">\n"
		+ "                            <a href=\"/%ec%a7%81%eb%ac%b4/-/senior-software-engineer-product-engineering-eats/24450/16871488\" data-job-id=\"16871488\">\n"
		+ "                                <h3 class=\"searched-job-title\">Senior, Software Engineer (Product Engineering Eats)</h3>\n"
		+ "                                    <span class=\"searched-job-location\">&#xC11C;&#xC6B8;,  &#xB300;&#xD55C;&#xBBFC;&#xAD6D;</span>\n"
		+ "            \n"
		+ "                            </a>\n"
		+ "                            <div class=\"job-detail-buttons search-result-detail-buttons\">\n"
		+ "                                    <button type=\"button\" aria-label=\"Save Job\" class=\"js-save-job-btn\" data-job-id=\"16871488\" data-org-id=\"24450\"></button>\n"
		+ "                            </div>\n"
		+ "                        </li>\n"
		+ "                        <li class=\"searched-job-item\">\n"
		+ "                            <a href=\"/%ec%a7%81%eb%ac%b4/-/sr-manager-back-end-engineering-query-understanding/24450/16709705\" data-job-id=\"16709705\">\n"
		+ "                                <h3 class=\"searched-job-title\">Sr. Manager, Back-end Engineering (Query Understanding)</h3>\n"
		+ "                                    <span class=\"searched-job-location\">&#xC11C;&#xC6B8;,  &#xB300;&#xD55C;&#xBBFC;&#xAD6D;</span>\n"
		+ "            \n"
		+ "                            </a>\n"
		+ "                            <div class=\"job-detail-buttons search-result-detail-buttons\">\n"
		+ "                                    <button type=\"button\" aria-label=\"Save Job\" class=\"js-save-job-btn\" data-job-id=\"16709705\" data-org-id=\"24450\"></button>\n"
		+ "                            </div>\n"
		+ "                        </li>\n"
		+ "                        <li class=\"searched-job-item\">\n"
		+ "                            <a href=\"/%ec%a7%81%eb%ac%b4/-/qa-engineer-product-service/24450/16759222\" data-job-id=\"16759222\">\n"
		+ "                                <h3 class=\"searched-job-title\">QA Engineer (Product Service)</h3>\n"
		+ "                                    <span class=\"searched-job-location\">&#xC11C;&#xC6B8;,  &#xB300;&#xD55C;&#xBBFC;&#xAD6D;</span>\n"
		+ "            \n"
		+ "                            </a>\n"
		+ "                            <div class=\"job-detail-buttons search-result-detail-buttons\">\n"
		+ "                                    <button type=\"button\" aria-label=\"Save Job\" class=\"js-save-job-btn\" data-job-id=\"16759222\" data-org-id=\"24450\"></button>\n"
		+ "                            </div>\n"
		+ "                        </li>\n"
		+ "                </ul>\n"
		+ "<section id=\"pagination-bottom\" class=\"pagination\" role=\"navigation\">\n"
		+ "            <div class=\"pagination-all\">\n"
		+ "                <a class=\"pagination-show-all\" href=\"#\">&#xBAA8;&#xB450; &#xBCF4;&#xAE30;</a>\n"
		+ "            </div>\n"
		+ "        <div class=\"pagination-page-count\">\n"
		+ "            <label class=\"pagination-current-label\" for=\"pagination-current-bottom\"><b>&#xB2E4;&#xB978; &#xD398;&#xC774;&#xC9C0;&#xB85C; &#xAC74;&#xB108;&#xB6F0;&#xB824;&#xBA74; &#xC22B;&#xC790;&#xB97C; &#xC785;&#xB825;&#xD558;&#xC2ED;&#xC2DC;&#xC624;. &#xD604;&#xC7AC; &#xD398;&#xC774;&#xC9C0;&#xC5D0; &#xC788;&#xC2B5;&#xB2C8;&#xB2E4;. 1 / 3.</b>&#xD398;&#xC774;&#xC9C0;</label><input class=\"pagination-current\" id=\"pagination-current-bottom\" max=\"3\" min=\"1\" type=\"number\" value=\"1\"></input><span class=\"pagination-total-pages\">/ 3</span><button class=\"pagination-page-jump\" type=\"button\">&#xC774;&#xB3D9;</button>\n"
		+ "        </div>\n"
		+ "        <div class=\"pagination-paging\">\n"
		+ "            <a aria-hidden=\"true\" class=\"prev disabled\" href=\"/%EA%B2%80%EC%83%89-%EC%A7%81%EB%AC%B4/%EB%8C%80%ED%95%9C%EB%AF%BC%EA%B5%AD&amp;p=1\" rel=\"nofollow\">&#xC774;&#xC804; &#xD398;&#xC774;&#xC9C0;</a>\n"
		+ "            <a class=\"next\" href=\"/%EA%B2%80%EC%83%89-%EC%A7%81%EB%AC%B4/%EB%8C%80%ED%95%9C%EB%AF%BC%EA%B5%AD&amp;p=2\" rel=\"nofollow\">&#xB2E4;&#xC74C; &#xD398;&#xC774;&#xC9C0;</a>\n"
		+ "        </div>\n"
		+ "    </section>            </section>\n"
		+ "    </section>\n"
		+ "\n"
		+ "\n"
		+ "    </div>\n"
		+ "</div>\n"
		+ "\n"
		+ "\n"
		+ "    <section class=\"job-alert-form-section\">\n"
		+ "        <div class=\"wrapper\">\n"
		+ "            <div class=\"container\">\n"
		+ "        \t    <form id=\"form-e9c9b7cca3\" class=\"data-form  \" action=\"/form/submit\" data-success-message=\"Your subscription was submitted successfully.\" data-error-message=\"There was an error processing your request.\" data-close-text=\"Close\" data-form-type=\"Job Alert\">\n"
		+ "        \t        <div class=\"job-alert-form\">\n"
		+ "        \t            \n"
		+ "                    \t\t    <h3 class=\"form-display-heading\">&#xCC44;&#xC6A9;&#xACF5;&#xACE0; &#xC54C;&#xB9BC; &#xC2E0;&#xCCAD;&#xD558;&#xAE30;</h3>\n"
		+ "                    \t\n"
		+ "\n"
		+ "                \n"
		+ "<p class=\"form-field required\"><label for=\"form-field-87411636dc\">&#xC774;&#xBA54;&#xC77C; &#xC8FC;&#xC18C;</label><input aria-required=\"true\" data-val=\"true\" data-val-length-max=\"255\" data-val-regex=\"Please enter a valid email address.\" data-val-regex-pattern=\"^[a-zA-Z0-9-.!#$%&amp;&#x27;*&#x2B;/=?^_`{|}~&#xE0;-&#xFF;&#xC0;-&#xDF;]&#x2B;@[a-zA-Z0-9-]&#x2B;(?:\\.[a-zA-Z0-9-]&#x2B;)&#x2B;$\" data-val-required=\"This field is required.\" id=\"form-field-87411636dc\" maxlength=\"255\" name=\"EmailAddress\" pattern=\"^[a-zA-Z0-9-.!#$%&amp;&#x27;*&#x2B;/=?^_`{|}~&#xE0;-&#xFF;&#xC0;-&#xDF;]&#x2B;@[a-zA-Z0-9-]&#x2B;(?:\\.[a-zA-Z0-9-]&#x2B;)&#x2B;$\" placeholder=\"&#xC774;&#xBA54;&#xC77C;&#xC744; &#xC785;&#xB825;&#xD558;&#xC138;&#xC694;\" required=\"required\" type=\"text\" /><span class=\"instruction-text\"></span><span class=\"field-validation-valid\" data-valmsg-for=\"EmailAddress\" data-valmsg-replace=\"true\" role=\"status\"></span></p><fieldset class=\"form-field required\" data-ajax-category=\"/Keywords/GetAvailableCategories?displayname=\" data-ajax-location=\"/Keywords/GetAvailableLocations?displayname=\" data-all-jobs-text=\"All Jobs\" data-both-required=\"False\" data-id=\"24450\" data-multiselect-enabled=\"false\" data-site-id=\"0\"><legend>Interested In</legend><span class=\"instruction-text\">Select a job category from the list of options. Select a location from the list of options. Finally, click &#x201C;Add&#x201D; to create your job alert.</span><span class=\"field-validation-valid\" data-valmsg-for=\"Category\" data-valmsg-replace=\"true\" role=\"status\"></span><p><label for=\"form-field-9170fd9a98-category\">&#xCC44;&#xC6A9; &#xBD84;&#xC57C;*</label><select autocomplete=\"off\" class=\"keyword-category\" data-keyword-list=\"form-field-9170fd9a98-keywords\" data-val=\"true\" data-val-requiredkeyword=\"This field is required.\" id=\"form-field-9170fd9a98-category\" name=\"Category\" required=\"required\"><option value=\"\">채용 분야를 선택하세요</option><option value=\"63827\">Audit</option><option value=\"62773\">Business Planning</option><option value=\"62774\">Business Support Service</option><option value=\"63828\">Contents UX</option><option value=\"62916\">Customer Services</option><option value=\"62812\">Data Engineering</option><option value=\"63872\">Delivery Support</option><option value=\"63523\">E-Commerce Operations</option><option value=\"62824\">FC Support</option><option value=\"62273\">Finance</option><option value=\"62813\">FinTech Business</option><option value=\"62775\">HR</option><option value=\"62815\">Infra Engineering</option><option value=\"63829\">Legal</option><option value=\"62816\">Logistics Planning</option><option value=\"62814\">Marketing & Advertising</option><option value=\"62817\">Merchandising Support</option><option value=\"62776\">Product Management</option><option value=\"62818\">Retail</option><option value=\"62819\">Sales and Account Management</option><option value=\"63831\">SCM</option><option value=\"62820\">Security Technology</option><option value=\"62822\">Software Development Engineers</option><option value=\"62777\">Tech Management</option><option value=\"62778\">UX</option></select></p><p><label for=\"form-field-9170fd9a98-location\">&#xC9C0;&#xC5ED;</label><select autocomplete=\"off\" class=\"keyword-location\" data-keyword-list=\"form-field-9170fd9a98-keywords\" data-location-facet-type=\"4\" data-temp-location-facet-type=\"4\" data-val=\"true\" data-val-requiredkeyword=\"This field is required.\" id=\"form-field-9170fd9a98-location\" name=\"Location\" required=\"required\"><option value=\"\">지역을 선택하세요</option><option value=\"6252001-5332921-5387877\">리버사이드, 미국</option><option value=\"6252001-5332921-5375480\">마운틴뷰, 미국</option><option value=\"1814991-2038349-1816670\">베이징, 중국</option><option value=\"1814991-1796231-1796236\">상하이, 중국</option><option value=\"1835841-1835847-1835848\">서울, 대한민국</option><option value=\"1814991-1809935-1795565\">선전, 중국</option><option value=\"6252001-5815135-5809844\">시애틀, 미국</option></select></p><button class=\"keyword-add\" disabled=\"disabled\" type=\"button\">&#xCD94;&#xAC00;</button><ul class=\"keyword-selected\" data-keyword-id=\"form-field-9170fd9a98-keywords\" data-list-name=\"JobAlertCategoryLocation\"><li data-category-facet-type=\"1\" data-category-name=\"Software Development Engineers\" data-category-term=\"62822\" data-custom-facet-name=\"ALL\" data-custom-facet-term=\"ALL\" data-custom-facet-value=\"\" data-keyword-id=\"form-field-9170fd9a98-keywords\" data-location-facet-type=\"2\" data-location-name=\"&#xB300;&#xD55C;&#xBBFC;&#xAD6D;\" data-location-term=\"1835841\"><span class=\"keyword-text\">Software Development Engineers, &#xB300;&#xD55C;&#xBBFC;&#xAD6D;</span><a aria-label=\"Remove Software Development Engineers, &#xB300;&#xD55C;&#xBBFC;&#xAD6D;\" class=\"keyword-remove\" href=\"#\">Remove</a></li><li class=\"keyword-template\" data-category-facet-type=\"\" data-category-name=\"\" data-category-term=\"\" data-custom-facet-name=\"ALL\" data-custom-facet-term=\"ALL\" data-custom-facet-value=\"\" data-keyword-id=\"form-field-9170fd9a98-keywords\" data-location-facet-type=\"\" data-location-name=\"\" data-location-term=\"\" style=\"display: none;\"><span class=\"keyword-text\"></span><a aria-label=\"Remove\" class=\"keyword-remove\" href=\"#\">Remove</a></li></ul></fieldset>                \t\t\n"
		+ "                \t\t\n"
		+ "                \t    <p class=\"form-field confirm-email\" aria-hidden=\"true\" style=\"display:block;height:0;overflow:hidden;position:absolute;text-indent:-9999em;width:0;z-index:-1\">\n"
		+ "                \t\t    <label aria-hidden=\"true\" for=\"form-field-2\">Confirm Email</label>\n"
		+ "                \t\t    <input aria-hidden=\"true\" autocomplete=\"off\" id=\"form-field-2\" name=\"EmailConfirm\" tabindex=\"-1\" type=\"text\" value=\"\" />\n"
		+ "                \t\t</p>\n"
		+ "                \t\t\t<input id=\"form-type-6b65eb2adf\" name=\"FormType\" type=\"hidden\" Value=\"JobAlert\" /><input id=\"module-name-6b65eb2adf\" name=\"ModuleName\" type=\"hidden\" Value=\"Job Alert Form\" /><input id=\"job-id-6b65eb2adf\" name=\"JobId\" type=\"hidden\" Value=\"\" /><input id=\"job-organization-id-6b65eb2adf\" name=\"JobOrganizationId\" type=\"hidden\" Value=\"24450\" /><input id=\"redirect-url-6b65eb2adf\" name=\"RedirectUrl\" type=\"hidden\" Value=\"\" /><input id=\"page-url-6b65eb2adf\" name=\"PageUrl\" type=\"hidden\" Value=\"rocketyourcareer.kr.coupang.com:80/%EA%B2%80%EC%83%89-%EC%A7%81%EB%AC%B4/%EB%8C%80%ED%95%9C%EB%AF%BC%EA%B5%AD?orgIds=24450&amp;alp=1835841&amp;alt=2&amp;ac=62822&amp;p=1\" /><input id=\"page-name-6b65eb2adf\" name=\"PageName\" type=\"hidden\" Value=\"Search Results\" /><input id=\"page-type-6b65eb2adf\" name=\"PageType\" type=\"hidden\" Value=\"Search\" />\n"
		+ "                \t\t<div class=\"form-field submit job-alert-submit\">\n"
		+ "                    \t\t<div class=\"button-slant button-reverse input-button\">\n"
		+ "                                <div class=\"button-border\"></div>\n"
		+ "                                <div class=\"button-border button-bottom\"></div>\n"
		+ "                                <div class=\"button-contents\"><span><input type=\"submit\" value=\"&#xC81C;&#xCD9C;\"></span></div>\n"
		+ "                            </div>   \n"
		+ "                \t\t</div>\n"
		+ "                \t\t    \n"
		+ "                \t\t<p class=\"form-field form-message\"></p>\n"
		+ "                    \t\n"
		+ "        \t        </div>\n"
		+ "        \t\t</form>\n"
		+ "        \t</div>\n"
		+ "        </div>\n"
		+ "\t</section>\n"
		+ "\n"
		+ "\n"
		+ "\n"
		+ "\n"
		+ "\n"
		+ "\n"
		+ "\t\t\n"
		+ "\t\t\n"
		+ "\t</main>\n"
		+ "\t</div>\n"
		+ "</body>\n"
		+ "</html>";
}