package com.mino.devjob.book.service;

import java.util.function.Function;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.web.reactive.function.client.WebClient;

import com.mino.devjob.book.model.Book;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import reactor.test.StepVerifier;

@ExtendWith(MockitoExtension.class)
class CrawlYes24ServiceTest {
	@InjectMocks
	private CrawlYes24Service crawlYes24Service;
	@Mock
	private WebClient webClientMock;
	@Mock
	private WebClient.RequestHeadersSpec requestHeadersMock;
	@Mock
	private WebClient.RequestHeadersUriSpec requestHeadersUriMock;
	@Mock
	private WebClient.ResponseSpec responseMock;

	@Test
	void crawl() {
		Mockito.when(webClientMock.get()).thenReturn(requestHeadersUriMock);
		Mockito.when(requestHeadersUriMock.uri(Mockito.any(Function.class))).thenReturn(requestHeadersMock);
		Mockito.when(requestHeadersMock.retrieve()).thenReturn(responseMock);
		Mockito.when(responseMock.bodyToMono(String.class)).thenReturn(Mono.just(str));

		Flux<Book> bookFlux = crawlYes24Service.crawl();

		StepVerifier.create(bookFlux)
			.expectNextCount(12)
			.verifyComplete();
	}

	private String str = "<!DOCTYPE html >\n"
		+ "<html lang=\"ko\">\n"
		+ "\n"
		+ "<body>\n"
		+ "<div id=\"yesWrap\" class=\"\">\n"
		+ "    <div id=\"cateSubWrap\" class=\"cateSubArea clearfix\">\n"
		+ "\n"
		+ "\n"
		+ "        <!-- ######################### 오른쪽 영역 시작 ######################### -->\n"
		+ "        <div class=\"cateSubRgt\">\n"
		+ "            <!-- 중앙 요소 리스트 -->\n"
		+ "            <!-- 기본형리스트 시작 -->\n"
		+ "            <div class=\"cCont_listArea\" id=\"category_layout\">\n"
		+ "                <ul class=\"clearfix\">\n"
		+ "\n"
		+ "                    <li>\n"
		+ "                        <div class=\"cCont_goodsSet\">\n"
		+ "                            <p class=\"goods_img\">\n"
		+ "                    <span class=\"goods_imgSet\">\n"
		+ "                        \n"
		+ "                        <span class=\"imgBdr\"> \n"
		+ "\t\t                    <a href=\"/Product/Goods/92426926\">\n"
		+ "\t\t\t                    <img src=\"http://image.yes24.com/goods/92426926/L\" alt=\"핵심만 콕! 쿠버네티스\" border=\"0\"/>\n"
		+ "\t\t\t                </a>\n"
		+ "                        </span>\n"
		+ "                    </span>\n"
		+ "\n"
		+ "                            </p>\n"
		+ "\n"
		+ "                            <div class=\"goods_info\">\n"
		+ "\n"
		+ "                                <div class=\"goods_keynote\">\n"
		+ "                                    <span class='iconC reserv'><em class='txt'>예약판매</em></span>\n"
		+ "\n"
		+ "                                </div>\n"
		+ "\n"
		+ "                                <div class=\"goods_name\">\n"
		+ "                                    <span class=\"gd_nameF\"></span>\n"
		+ "                                    <a href=\"/Product/Goods/92426926\">핵심만 콕! 쿠버네티스</a>\n"
		+ "                                    <span class=\"gd_nameE\">쿠버네티스의 핵심을 실습하고 이해하는</span>\n"
		+ "                                    <span class=\"gd_feature\"> </span>\n"
		+ "\n"
		+ "                                    <a href=\"/Product/Goods/92426926\" class=\"bgYUI ico_nWin\" target=\"_blank\"></a>\n"
		+ "\n"
		+ "                                </div>\n"
		+ "\n"
		+ "                                <div class=\"goods_pubGrp\">\n"
		+ "                        \n"
		+ "                        <span class=\"goods_auth\">\n"
		+ "                        <a href=\"http://www.yes24.com//SearchCorner/Result?domain=ALL&author_yn=Y&query=&auth_no=312558\" target=\"_blank\">유홍근</a> 저                          \n"
		+ "                        \n"
		+ "                        </span>\n"
		+ "\n"
		+ "                                    <em class=\"divi\">|</em>\n"
		+ "\n"
		+ "                                    <span class=\"goods_pub\">비제이퍼블릭(BJ퍼블릭)</span>\n"
		+ "\n"
		+ "                                    <em class=\"divi\">|</em>\n"
		+ "\n"
		+ "                                    <span class=\"goods_date\">2020년 09월</span>\n"
		+ "\n"
		+ "                                </div>\n"
		+ "\n"
		+ "                                <!--특징2-->\n"
		+ "\n"
		+ "                                <div class=\"goods_price\">\n"
		+ "\n"
		+ "                                    <em class=\"yes_b\">28,800</em>원\n"
		+ "\n"
		+ "                                    <span class=\"goods_benefit\">(10% 할인)</span>\n"
		+ "\n"
		+ "                                    <em class=\"bgYUI ico_point\">포인트적립</em> 1,600원\n"
		+ "\n"
		+ "                                </div>\n"
		+ "\n"
		+ "\n"
		+ "\n"
		+ "                                <div class=\"goods_deli\">\n"
		+ "\n"
		+ "                                    <strong class=\"deli_act\">2020년 09월 22일 발송예정 (예약판매)</strong>\n"
		+ "                                    (예정일 이후 1~2일 이내 받을 수 있습니다.)\n"
		+ "\n"
		+ "                                </div>\n"
		+ "\n"
		+ "                                <!--분철서비스 시작-->\n"
		+ "\n"
		+ "                                <!--분철서비스 종료-->\n"
		+ "\n"
		+ "                                <!--알림신청 시작-->\n"
		+ "\n"
		+ "                                <!--알림신청 종료-->\n"
		+ "\n"
		+ "                                <!--구매시참고문구 시작-->\n"
		+ "\n"
		+ "                                <!--구매시참고문구 종료-->\n"
		+ "\n"
		+ "\n"
		+ "                                <div class=\"goods_read\">\n"
		+ "                                    쿠버네티스를 처음 접하시는 분을 위해 준비했다. 컨테이너, 쿠버네티스 기술에 대해 잘 모르더라도 이 책의 예제를 따라하다보면 어느새 쿠버네티스의 매력에 푹 빠질 것입니다. 쿠버네티스 입문서로 시작하기에 최고의 선택, 여러분도 쿠버네티스라는 거인의 어깨 위에 올라서서 클라우드 네이티브가 꿈꾸는 세상을 바라...\n"
		+ "                                </div>\n"
		+ "\n"
		+ "\n"
		+ "                            </div>\n"
		+ "\n"
		+ "                            <input type=\"hidden\" name = \"ORD_GOODS_OPT\" value=\"{&quot;goods_no&quot;:92426926,&quot;goods_seq&quot;:1,&quot;order_limit_yn&quot;:&quot;N&quot;,&quot;order_remain_count&quot;:0,&quot;event_no&quot;:0,&quot;add_cart_yn&quot;:&quot;Y&quot;,&quot;goods_state&quot;:&quot;01&quot;,&quot;order_limit_count&quot;:1000,&quot;resource_key&quot;:&quot;01&quot;,&quot;limit_age_yn&quot;:&quot;&quot;,&quot;limit_age&quot;:0,&quot;member_age&quot;:0,&quot;goods_name&quot;:&quot;핵심만 콕! 쿠버네티스&quot;,&quot;noint_quotamonth&quot;:0,&quot;min_cnt&quot;:0,&quot;max_cnt&quot;:0,&quot;opt_salepr&quot;:0,&quot;opt_yn&quot;:&quot;N&quot;,&quot;opt_inst_yn&quot;:&quot;N&quot;,&quot;flat_rate_yn&quot;:null,&quot;rent_goods_yn&quot;:&quot;N&quot;,&quot;bookclue_yn&quot;:null}\" />\n"
		+ "                            <div class=\"goods_btn\">\n"
		+ "\n"
		+ "\n"
		+ "                                <div class=\"etcRow\">\n"
		+ "                                    <span class=\"chkBox\"><input name=\"ORD_GOODS_CHKBOX\" type=\"checkbox\" value=\"\" class=\"basic\"/></span>\n"
		+ "\n"
		+ "\n"
		+ "                                    <span class=\"numBox\" style=\"display:block\">\n"
		+ "\t\t\t\t\t\t\t    <span class=\"yesIpt ipt_wSizeF\"><input type=\"text\" title=\"수량설정\" value=\"1\" class=\"ac yes_m\" name=\"ORD_GOODS_CNT\" readonly=\"readonly\"/></span>\n"
		+ "\t\t\t\t\t\t\t    <button type=\"button\" class=\"minus\" onclick=\"yes24GU.downOrderCount(0)\"><span class=\"bgYUI\">수량감소</span></button>\n"
		+ "                                <button type=\"button\" class=\"plus\" onclick=\"yes24GU.upOrderCount(0)\"><span class=\"bgYUI\">수량증가</span></button>\n"
		+ "\t\t\t\t\t\t    </span>\n"
		+ "\n"
		+ "                                </div>\n"
		+ "\n"
		+ "\n"
		+ "                                <a href=\"javascript:void(0)\" onclick=\"yes24GU.addToCartSetPosByOnlyOneGoodsNoNew(92426926,0, '001001003025',this);\" class=\"btnC btn_blue\" id=\"btnCart0\"><span class=\"bWrap\"><em class=\"txt\">카트에 넣기</em></span></a>\n"
		+ "                                <a href=\"javascript:yes24GU.buyWithoutCart(0, '001001003025', false);\" class=\"btnC btn_sBlue\"><span class=\"bWrap\"><em class=\"txt\">바로구매</em></span></a>\n"
		+ "\n"
		+ "\n"
		+ "\n"
		+ "                                <a href=\"javascript:yes24GU.addToMyListByIndex(0);\" class=\"btnC\"><span class=\"bWrap\"><em class=\"txt\">리스트에 넣기</em></span></a>\n"
		+ "\n"
		+ "\n"
		+ "                            </div>\n"
		+ "\n"
		+ "                        </div>\n"
		+ "                    </li>\n"
		+ "\n"
		+ "                    <li>\n"
		+ "                        <div class=\"cCont_goodsSet\">\n"
		+ "                            <p class=\"goods_img\">\n"
		+ "                    <span class=\"goods_imgSet\">\n"
		+ "                        \n"
		+ "                        <span class=\"imgBdr\"> \n"
		+ "\t\t                    <a href=\"/Product/Goods/92151448\">\n"
		+ "\t\t\t                    <img src=\"http://image.yes24.com/goods/92151448/L\" alt=\"JSP &amp; MySQL Web Server Programming\" border=\"0\"/>\n"
		+ "\t\t\t                </a>\n"
		+ "                        </span>\n"
		+ "                    </span>\n"
		+ "\n"
		+ "                            </p>\n"
		+ "\n"
		+ "                            <div class=\"goods_info\">\n"
		+ "\n"
		+ "                                <div class=\"goods_name\">\n"
		+ "                                    <span class=\"gd_nameF\">기초부터 응용까지 다루는</span>\n"
		+ "                                    <a href=\"/Product/Goods/92151448\">JSP &amp; MySQL Web Server Programming</a>\n"
		+ "                                    <span class=\"gd_nameE\"></span>\n"
		+ "                                    <span class=\"gd_feature\"> </span>\n"
		+ "\n"
		+ "                                    <a href=\"/Product/Goods/92151448\" class=\"bgYUI ico_nWin\" target=\"_blank\"></a>\n"
		+ "\n"
		+ "                                </div>\n"
		+ "\n"
		+ "                                <div class=\"goods_pubGrp\">\n"
		+ "                        \n"
		+ "                        <span class=\"goods_auth\">\n"
		+ "                        <a href=\"http://www.yes24.com//SearchCorner/Result?domain=ALL&author_yn=Y&query=&auth_no=271731\" target=\"_blank\">이태동</a> 저                          \n"
		+ "                        \n"
		+ "                        </span>\n"
		+ "\n"
		+ "                                    <em class=\"divi\">|</em>\n"
		+ "\n"
		+ "                                    <span class=\"goods_pub\">북스홀릭퍼블리싱</span>\n"
		+ "\n"
		+ "                                    <em class=\"divi\">|</em>\n"
		+ "\n"
		+ "                                    <span class=\"goods_date\">2020년 09월</span>\n"
		+ "\n"
		+ "                                </div>\n"
		+ "\n"
		+ "                                <!--특징2-->\n"
		+ "\n"
		+ "                                <div class=\"goods_price\">\n"
		+ "\n"
		+ "                                    <em class=\"yes_b\">33,000</em>원\n"
		+ "\n"
		+ "                                    <em class=\"bgYUI ico_point\">포인트적립</em> 0원\n"
		+ "\n"
		+ "                                </div>\n"
		+ "\n"
		+ "\n"
		+ "\n"
		+ "                                <div class=\"goods_deli\">\n"
		+ "\n"
		+ "                                    도착 예상일 : 지금 주문하면 <strong class=\"deli_act\">오늘</strong> 받을 수 있습니다.\n"
		+ "\n"
		+ "                                </div>\n"
		+ "\n"
		+ "                                <!--분철서비스 시작-->\n"
		+ "\n"
		+ "                                <!--분철서비스 종료-->\n"
		+ "\n"
		+ "                                <!--알림신청 시작-->\n"
		+ "\n"
		+ "                                <!--알림신청 종료-->\n"
		+ "\n"
		+ "                                <!--구매시참고문구 시작-->\n"
		+ "\n"
		+ "                                <!--구매시참고문구 종료-->\n"
		+ "\n"
		+ "\n"
		+ "                                <div class=\"goods_read\">\n"
		+ "                                    웹 서버 프로그래밍 개발 입문서로서 JSP와 Servlet, 그리고 MySQL과 JDBC에 대한 기능을 기초부터 응용까지 체계적으로 내용을 수록하였으며, 학습예제 실행 결과화면과 그림을 본문에 삽입하여 독자들이 쉽게 학습할 수 있도록 구성하였다. JSP 웹 서버 프로그래밍의 기능을 이론과 실습으로 사용자가 쉽게 학습할 수 있...\n"
		+ "                                </div>\n"
		+ "\n"
		+ "\n"
		+ "                            </div>\n"
		+ "\n"
		+ "                            <input type=\"hidden\" name = \"ORD_GOODS_OPT\" value=\"{&quot;goods_no&quot;:92151448,&quot;goods_seq&quot;:1,&quot;order_limit_yn&quot;:&quot;N&quot;,&quot;order_remain_count&quot;:0,&quot;event_no&quot;:0,&quot;add_cart_yn&quot;:&quot;Y&quot;,&quot;goods_state&quot;:&quot;02&quot;,&quot;order_limit_count&quot;:0,&quot;resource_key&quot;:&quot;01&quot;,&quot;limit_age_yn&quot;:&quot;N&quot;,&quot;limit_age&quot;:0,&quot;member_age&quot;:0,&quot;goods_name&quot;:&quot;JSP &amp;amp; MySQL Web Server Programming&quot;,&quot;noint_quotamonth&quot;:0,&quot;min_cnt&quot;:0,&quot;max_cnt&quot;:0,&quot;opt_salepr&quot;:0,&quot;opt_yn&quot;:&quot;N&quot;,&quot;opt_inst_yn&quot;:&quot;N&quot;,&quot;flat_rate_yn&quot;:null,&quot;rent_goods_yn&quot;:&quot;N&quot;,&quot;bookclue_yn&quot;:null}\" />\n"
		+ "                            <div class=\"goods_btn\">\n"
		+ "\n"
		+ "\n"
		+ "                                <div class=\"etcRow\">\n"
		+ "                                    <span class=\"chkBox\"><input name=\"ORD_GOODS_CHKBOX\" type=\"checkbox\" value=\"\" class=\"basic\"/></span>\n"
		+ "\n"
		+ "\n"
		+ "                                    <span class=\"numBox\" style=\"display:block\">\n"
		+ "\t\t\t\t\t\t\t    <span class=\"yesIpt ipt_wSizeF\"><input type=\"text\" title=\"수량설정\" value=\"1\" class=\"ac yes_m\" name=\"ORD_GOODS_CNT\" readonly=\"readonly\"/></span>\n"
		+ "\t\t\t\t\t\t\t    <button type=\"button\" class=\"minus\" onclick=\"yes24GU.downOrderCount(1)\"><span class=\"bgYUI\">수량감소</span></button>\n"
		+ "                                <button type=\"button\" class=\"plus\" onclick=\"yes24GU.upOrderCount(1)\"><span class=\"bgYUI\">수량증가</span></button>\n"
		+ "\t\t\t\t\t\t    </span>\n"
		+ "\n"
		+ "                                </div>\n"
		+ "\n"
		+ "\n"
		+ "                                <a href=\"javascript:void(0)\" onclick=\"yes24GU.addToCartSetPosByOnlyOneGoodsNoNew(92151448,1, '001001003025',this);\" class=\"btnC btn_blue\" id=\"btnCart1\"><span class=\"bWrap\"><em class=\"txt\">카트에 넣기</em></span></a>\n"
		+ "                                <a href=\"javascript:yes24GU.buyWithoutCart(1, '001001003025', false);\" class=\"btnC btn_sBlue\"><span class=\"bWrap\"><em class=\"txt\">바로구매</em></span></a>\n"
		+ "\n"
		+ "\n"
		+ "\n"
		+ "                                <a href=\"javascript:yes24GU.addToMyListByIndex(1);\" class=\"btnC\"><span class=\"bWrap\"><em class=\"txt\">리스트에 넣기</em></span></a>\n"
		+ "\n"
		+ "\n"
		+ "                            </div>\n"
		+ "\n"
		+ "                        </div>\n"
		+ "                    </li>\n"
		+ "\n"
		+ "                    <li>\n"
		+ "                        <div class=\"cCont_goodsSet\">\n"
		+ "                            <p class=\"goods_img\">\n"
		+ "                    <span class=\"goods_imgSet\">\n"
		+ "                        \n"
		+ "                        <span class=\"imgBdr\"> \n"
		+ "\t\t                    <a href=\"/Product/Goods/91923749\">\n"
		+ "\t\t\t                    <img src=\"http://image.yes24.com/goods/91923749/L\" alt=\"AWS 공인 솔루션스 아키텍트 올인원 스터디 가이드 - 어소시에이트\" border=\"0\"/>\n"
		+ "\t\t\t                </a>\n"
		+ "                        </span>\n"
		+ "                    </span>\n"
		+ "\n"
		+ "                                <a href=\"javascript:yes24GU.openPreviewCheck(91923749);\" class=\"btnC btn_preview\"><span class=\"bWrap\"><em class=\"txt\">미리보기</em></span></a>\n"
		+ "\n"
		+ "                            </p>\n"
		+ "\n"
		+ "                            <div class=\"goods_info\">\n"
		+ "\n"
		+ "                                <div class=\"goods_name\">\n"
		+ "                                    <span class=\"gd_nameF\"></span>\n"
		+ "                                    <a href=\"/Product/Goods/91923749\">AWS 공인 솔루션스 아키텍트 올인원 스터디 가이드 - 어소시에이트</a>\n"
		+ "                                    <span class=\"gd_nameE\"></span>\n"
		+ "                                    <span class=\"gd_feature\"> </span>\n"
		+ "\n"
		+ "                                    <a href=\"/Product/Goods/91923749\" class=\"bgYUI ico_nWin\" target=\"_blank\"></a>\n"
		+ "\n"
		+ "                                </div>\n"
		+ "\n"
		+ "                                <div class=\"goods_pubGrp\">\n"
		+ "                        \n"
		+ "                        <span class=\"goods_auth\">\n"
		+ "                        <a href=\"http://www.yes24.com//SearchCorner/Result?domain=ALL&author_yn=Y&query=&auth_no=310930\" target=\"_blank\">조이지트 배너지</a> 저/<a href=\"http://www.yes24.com//SearchCorner/Result?domain=ALL&author_yn=Y&query=&auth_no=202662\" target=\"_blank\">동준상</a> 역                          \n"
		+ "                        \n"
		+ "                        </span>\n"
		+ "\n"
		+ "                                    <em class=\"divi\">|</em>\n"
		+ "\n"
		+ "                                    <span class=\"goods_pub\">에이콘출판사</span>\n"
		+ "\n"
		+ "                                    <em class=\"divi\">|</em>\n"
		+ "\n"
		+ "                                    <span class=\"goods_date\">2020년 08월</span>\n"
		+ "\n"
		+ "                                </div>\n"
		+ "\n"
		+ "                                <!--특징2-->\n"
		+ "\n"
		+ "                                <div class=\"goods_price\">\n"
		+ "\n"
		+ "                                    <em class=\"yes_b\">29,700</em>원\n"
		+ "\n"
		+ "                                    <span class=\"goods_benefit\">(10% 할인)</span>\n"
		+ "\n"
		+ "                                    <em class=\"bgYUI ico_point\">포인트적립</em> 1,650원\n"
		+ "\n"
		+ "                                </div>\n"
		+ "\n"
		+ "\n"
		+ "\n"
		+ "                                <div class=\"goods_deli\">\n"
		+ "\n"
		+ "                                    도착 예상일 : 지금 주문하면 <strong class=\"deli_act\">오늘</strong> 받을 수 있습니다.\n"
		+ "\n"
		+ "                                </div>\n"
		+ "\n"
		+ "                                <!--분철서비스 시작-->\n"
		+ "\n"
		+ "                                <!--분철서비스 종료-->\n"
		+ "\n"
		+ "                                <!--알림신청 시작-->\n"
		+ "\n"
		+ "                                <!--알림신청 종료-->\n"
		+ "\n"
		+ "                                <!--구매시참고문구 시작-->\n"
		+ "\n"
		+ "                                <!--구매시참고문구 종료-->\n"
		+ "\n"
		+ "\n"
		+ "                                <div class=\"goods_read\">\n"
		+ "                                    AWS 공인 솔루션스 아키텍트 - 어소시에이트 자격을 취득하기 위한 SAA-C01 수험서로 출제되는 모든 영역에 대한 상세한 설명과 기출 문제, 정답, 해설을 제공한다. 클라우드 전문가이자 AWS의 현직 솔루션 아키텍트가 집필했다. AWS 공식 솔루션스 아키텍트 - 어소시에이트 자격 취득을 준비하고 있다면 이 책을 통해 AWS ...\n"
		+ "                                </div>\n"
		+ "\n"
		+ "\n"
		+ "                            </div>\n"
		+ "\n"
		+ "                            <input type=\"hidden\" name = \"ORD_GOODS_OPT\" value=\"{&quot;goods_no&quot;:91923749,&quot;goods_seq&quot;:1,&quot;order_limit_yn&quot;:&quot;N&quot;,&quot;order_remain_count&quot;:0,&quot;event_no&quot;:0,&quot;add_cart_yn&quot;:&quot;Y&quot;,&quot;goods_state&quot;:&quot;02&quot;,&quot;order_limit_count&quot;:1000,&quot;resource_key&quot;:&quot;01&quot;,&quot;limit_age_yn&quot;:&quot;&quot;,&quot;limit_age&quot;:0,&quot;member_age&quot;:0,&quot;goods_name&quot;:&quot;AWS 공인 솔루션스 아키텍트 올인원 스터디 가이드 - 어소시에이트&quot;,&quot;noint_quotamonth&quot;:0,&quot;min_cnt&quot;:0,&quot;max_cnt&quot;:0,&quot;opt_salepr&quot;:0,&quot;opt_yn&quot;:&quot;N&quot;,&quot;opt_inst_yn&quot;:&quot;N&quot;,&quot;flat_rate_yn&quot;:null,&quot;rent_goods_yn&quot;:&quot;N&quot;,&quot;bookclue_yn&quot;:null}\" />\n"
		+ "                            <div class=\"goods_btn\">\n"
		+ "\n"
		+ "\n"
		+ "                                <div class=\"etcRow\">\n"
		+ "                                    <span class=\"chkBox\"><input name=\"ORD_GOODS_CHKBOX\" type=\"checkbox\" value=\"\" class=\"basic\"/></span>\n"
		+ "\n"
		+ "\n"
		+ "                                    <span class=\"numBox\" style=\"display:block\">\n"
		+ "\t\t\t\t\t\t\t    <span class=\"yesIpt ipt_wSizeF\"><input type=\"text\" title=\"수량설정\" value=\"1\" class=\"ac yes_m\" name=\"ORD_GOODS_CNT\" readonly=\"readonly\"/></span>\n"
		+ "\t\t\t\t\t\t\t    <button type=\"button\" class=\"minus\" onclick=\"yes24GU.downOrderCount(2)\"><span class=\"bgYUI\">수량감소</span></button>\n"
		+ "                                <button type=\"button\" class=\"plus\" onclick=\"yes24GU.upOrderCount(2)\"><span class=\"bgYUI\">수량증가</span></button>\n"
		+ "\t\t\t\t\t\t    </span>\n"
		+ "\n"
		+ "                                </div>\n"
		+ "\n"
		+ "\n"
		+ "                                <a href=\"javascript:void(0)\" onclick=\"yes24GU.addToCartSetPosByOnlyOneGoodsNoNew(91923749,2, '001001003025',this);\" class=\"btnC btn_blue\" id=\"btnCart2\"><span class=\"bWrap\"><em class=\"txt\">카트에 넣기</em></span></a>\n"
		+ "                                <a href=\"javascript:yes24GU.buyWithoutCart(2, '001001003025', false);\" class=\"btnC btn_sBlue\"><span class=\"bWrap\"><em class=\"txt\">바로구매</em></span></a>\n"
		+ "\n"
		+ "\n"
		+ "\n"
		+ "                                <a href=\"javascript:yes24GU.addToMyListByIndex(2);\" class=\"btnC\"><span class=\"bWrap\"><em class=\"txt\">리스트에 넣기</em></span></a>\n"
		+ "\n"
		+ "\n"
		+ "                            </div>\n"
		+ "\n"
		+ "                        </div>\n"
		+ "                    </li>\n"
		+ "                </ul>\n"
		+ "            </div>\n"
		+ "            <!-- 기본형리스트 끝 -->\n"
		+ "            \n"
		+ "        </div>\n"
		+ "    </div>\n"
		+ "</div>\n"
		+ "</body>\n"
		+ "</html>\n";
}