apiVersion: v1
kind: Service
metadata:
  name: mongo-db
  labels:
    app: mongo-db
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app: mongo-db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db
  labels:
    app: mongo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
      - name: mongo-db
        image: mongo:latest
        securityContext:
          runAsUser: 501
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-vol

      volumes:
      - name: mongodb-vol
        hostPath:
          path: /Users/user/projects/my/dev-job/mongo/db
          type: Directory
